### PR TITLE
Add support for receiving traces over OTLP/gRPC

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Add the gRPC service for receiving OTLP traces, and plumb it through to `processor/otel`. Once this lands we can follow up with:
 - adding support for metrics
 - translating OpenTelemetry semantic conventions to our model (i.e. what's in elasticexporter in opentelemetry-collector-contrib)
 - (later) adding support for logs

We use an interceptor for ensuring clients are authorised. Auth works by setting the "Authorization" header (gRPC request metadata) just like in HTTP requests.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
~- [ ] Documentation has been updated~ (I will create a separate issue for this)

## How to test these changes

1. Run APM Server
2. Run opentelemetry-collector with the "otlp" exporter, pointed at APM Server, using the standard port (8200). It will be necessary to set `insecure: true` in the exporter config, unless APM Server is configured to use TLS.
3. Send some OpenTelemetry data to opentelemetry-collector, and ensure that it shows up in the APM app.
4. Configure APM Server with a secret token.
5. Run step 3 again, observe a failure due to invalid auth.
6. Add the secret token to the otlp exporter config, like `headers: {'Authorization': 'Bearer secret_token'}`, restart opentelemetry-collector
7. Run step 3 again, ensure the data shows up in the APM app again.

## Related issues

#4503

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

**Comment by bmorelli25** [comment]
How are you running opentelemetry-collector? I'm trying to run the docker [demo](https://opentelemetry.io/docs/collector/getting-started/#demo) and can't get it to work 😬 (almost definitely user-error and not because something is wrong with the PR).

**Review by simitt — APPROVED** [review]
LGTM

I teseted it through as described - works as expected

**Comment by simitt** [comment]
@bmorelli25 I run a small local app in go, basically following https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp#example-package-Insecure.

**Comment by axw** [comment]
Test failure is unrelated, see https://github.com/elastic/apm-server/issues/4692

**Comment by cyrille-leclerc** [comment]
I have successfully tested traces with 

* OpenTelemetry Collector 0.21
```yml 
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:4317'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      # cpu not supported on MacOS
      # cpu:
      load:
      memory:
processors:
  batch: null
exporters:
  logging:
    loglevel: info
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/elastic:
    endpoint: "localhost:8200"
    insecure: true
    headers:
      Authorization: "Bearer my_secret_token"
service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - prometheus
        - otlp/elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/elastic
```

* Java Agent opentelemetry-javaagent-all-0.16.1.jar
* 
```
export OTEL_RESOURCE_ATTRIBUTES=service.name=checkoutService,service.namespace=com-shoppingcart,service.version=1.0-SNAPSHOT,deployment.environment=staging
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:8200
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer my_secret_token"

java -javaagent:$PRGDIR/../.otel/opentelemetry-javaagent-all-0.16.1.jar \
     -Dio.opentelemetry.auto.slf4j.simpleLogger.defaultLogLevel=info \
     -classpath target/dependency/*:target/classes/ com.mycompany.checkout.CheckoutServiceServer
```

I have to double check metrics.

**Comment by axw** [comment]
Thanks for testing it out @cyrille-leclerc!

**Comment by cyrille-leclerc** [comment]
Successfully tested on Elastic Cloud Staging

```
extensions:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:4317'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      # cpu not supported on MacOS
      # cpu:
      load:
      memory:

processors:
  batch: null

exporters:
  logging:
    loglevel: info
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/elastic:
    endpoint: "abcd12345678901234567.apm.us-central1.gcp.foundit.no:443"
    insecure: false
    headers:
      Authorization: "Bearer ****************"
service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - prometheus
        - otlp/elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/elastic
  extensions: [zpages]
```

```
export OTEL_RESOURCE_ATTRIBUTES=service.name=frontend,service.namespace=com-shoppingcart,service.version=1.0-SNAPSHOT,deployment.environment=staging
export OTEL_EXPORTER_OTLP_ENDPOINT=https://abcd12345678901234567.apm.us-central1.gcp.foundit.no
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer ****************"

java -javaagent:$PRGDIR/../.otel/opentelemetry-javaagent-all-0.16.1.jar \
     -jar target/frontend-1.0-SNAPSHOT.jar
```

**Comment by simitt** [comment]
Tested with BC 2 - Worked with the elastic and the otel exporter.

**Comment by patpatpat123** [comment]
Hello team,

In this page, as well as in the official APM doc: https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html#instrument-apps-otel

We see this example being used every time: ```com.mycompany.checkout.CheckoutServiceServer```

Is it possible to make this example ```com.mycompany.checkout.CheckoutServiceServer``` available please?

Thank you

**Comment by axw** [comment]
@patpatpat123 I don't know if there even is any such code, or if it was just a made up example class name. If you're looking for a demo application to instrument with OpenTelemetry, then you should consider using OpenTelemetry Demo: https://github.com/open-telemetry/opentelemetry-demo

**Pull request merged**
