### PR TITLE
Add a _doc_count field for single-histogram metricsets

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

If a metricset is published with a single histogram, add a `_doc_count` field which is the sum of the histogram's counts. This will enable us to remove some `value_count` aggregations in the UI to determine the transaction count.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

1. Enable transaction metrics aggregation
2. Send some transactions
3. Check that the docs have `_doc_count` in them
4. Perform aggregations over the docs (e.g. terms agg on `transaction.name`), and check that the `doc_count` value in each bucket matches the number of transaction events aggregated.

## Related issues

Closes https://github.com/elastic/apm-server/issues/4474

### CODE REVIEW

**Review by simitt — COMMENTED** [review]
Code looks good and I tested the change - everything works as expected against ES `master`. 

Since `_doc_count` support was recently introduced, I also tested behavior against `7.9` ES. Writing the docs works fine, but running aggregations doesn't take the values into account. Since this impacts histogram functionality, I assume that Kibana would need to check for the ES version/indices when aggregating?

Screenshot 2021-01-25 at 15 24 13

Screenshot 2021-01-25 at 15 24 21

**Comment by dgieselaar** [comment]
@simitt Kibana is only expected to work against ES versions of the same minor/major, so it's not expected to support ES 7.9 when running Kibana 7.12.

**Comment by simitt** [comment]
Right! Perfectly fine then.

**Review by simitt — APPROVED** [review]

**Comment by axw** [comment]
Sorry about the force-push, forgot I was working on a non-draft PR. About to merge anyway.

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Pull request merged**
