### PR TITLE
Update changelog and release state.

### PR DESCRIPTION
**Pull request by simitt**
We need to update [APM release notes](https://www.elastic.co/guide/en/apm/get-started/7.0/apm-release-notes.html) for the beta-1 release.
@elastic/apm-ui @elastic/apm-agent-devs please let me know what we should add for your sections. 

We should get this out asap.

### CODE REVIEW

**Comment by formgeist** [comment]
I reckon the biggest the change for APM UI is the move to ECS and filtering out 6.x data. Perhaps a changelog that reads like this?

---

*APM UI*

- Breaking change: Moving to new data endpoints. We are filtering out 6.x or lower so if you want to keep your old data, migrate it using the Kibana Migration Assistant (in the Kibana Management section).
- Added support for frozen indices.

@elastic/apm-ui anything else that's critical to mention here?

**Comment by simitt** [comment]
@formgeist I think your suggestions are great for the 7.0.0 release, but I would not suggest that users use the migration script of the beta release to migrate their production data. They should wait for the 7.0.0 release for that. 

We can either add a disclaimer that the script should only be tried out on non-production data or not mention the migration script at all for now. WDYT? (cc @roncohen @graphaelli ).

**Comment by gregkalapos** [comment]
I'm not sure whether we should add this, and in case we add this how to formulate, but:
- We shipped the first preview release of the .NET APM Agent
- (the bad part:) If I remember correctly in Server 7.0 we removed intake v2, so the .NET preview agent won't work with it. I explicitly added to the agent blog/video that the agent is only tested with server 6.5 and 6.6, and 7.0 beta won't work with the first .NET preview agent.

**Comment by formgeist** [comment]
@simitt You're absolutely right, it makes sense for users to wait until GA to migrate their data. I can change the copy to simply add as a disclaimer that APM UI will only display 7.0 data or higher, but users can migrate their data using the migration assistant, but we recommend not doing so on production data. How does that sound?

**Comment by simitt** [comment]
WDYT about something along the lines of:
> We offer a Kibana Migration Assistant (in the Kibana Management section) to help you migrate your data. Be aware that this script is **not** supposed to be run on production data at this stage, as this is a beta release.

**Comment by formgeist** [comment]
@simitt Sounds good

**Comment by simitt** [comment]
@gregkalapos interesting. As you pointed out the agent will not work with 7.0 for now, so I suggest to not add this as it probably creates confusion.

**Comment by gregkalapos** [comment]
> @gregkalapos interesting. As you pointed out the agent will not work with 7.0 for now, so I suggest to not add this as it probably creates confusion.

👍 sounds good! I already work on migrating to intake v2, once that done, I think we can add it to a next release note.

**Pull request merged**
