### PR TITLE
Move setting of data_stream fields to processor

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Move the logic associated with setting data_stream fields out of model, into a model processor. Most of our tests will not run the model processor, hence why the data_stream fields disappear from approvals. Importantly, the TestFleetIntegration system test's approval file (which doesn't and shouldn't show up in the diff) retains the fields.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~
~- [ ] Documentation has been updated~

## How to test these changes

Non-functional change.

## Related issues

#4410
#4120
#3565

### CODE REVIEW

**Comment by axw** [comment]
Moving this back into draft while I fix conflicts, and remove `transform.Config`.

**Review by simitt — APPROVED** [review]
Great to get rid of a lot of the `*transformConfig` dependencies when transforming the events to beat events.

**Comment by axw** [comment]
@Mergifyio backport 7.x

**Pull request merged**
