### PR TITLE
Update config yml to reflect proper default vals.

### PR DESCRIPTION
**Pull request by simitt**
Since the configuration yml is not automatically updated on beats updates (as we differ in some sections), I manually compared and updated the config files, especially the default values.

### CODE REVIEW

**Comment by simitt** [comment]
@graphaelli I looked into the ssl handling in libbeat. It seems by default no ssl/tls config is loaded if nothing is commented in in the config file. So I'd say by default ssl is off. 
As soon as some ssl config is enabled though, the tls config is loaded. 
I changed the yml file to show `ssl.enabled:false`.

Let me know what you think.

**Comment by graphaelli** [comment]
Thanks for digging into it, I'm very surprised by this finding and think it's very confusing for users.  I think `ssl.enabled` should only be relevant where the protocol doesn't indicate that tls is desired (logstash/kafka vs https).  Given that changing that would involve a beats update, I think here we should a comment saying something like `# enable custom SSL settings - ssl.enabled: false`

**Comment by graphaelli** [comment]
I agree with you what you pointed out offline - the default is actually true since `nil/true` both enable this setting.  Revised proposal:

```
# enable custom SSL settings.  Set to false to ignore custom SSL settings for secure communication
# ssl.enabled: true
```

**Comment by simitt** [comment]
Thanks for the suggestion @graphaelli , I've update it.

**Comment by simitt** [comment]
Closing this for now, as it needs some more investigation.

**Pull request merged**
