### PR TITLE
kibana index pattern workarounds for non-indexed fields

### PR DESCRIPTION
**Pull request by graphaelli**
Fixes index pattern/tests.  To be replaced eventually by the nicer syntax in #1666.

### CODE REVIEW

**Comment by simitt** [comment]
jenkins, retest this please.

**Comment by simitt** [comment]
This is not working as `index: false` and `doc_values: false` don't seem to be allowed for `objects`.

**Comment by simitt** [comment]
@graphaelli could you please close this and reopen #1666 (without the changes in the vendored dir).

**Comment by graphaelli** [comment]
thanks for tracking that down, backports and libbeat sync complete, proceeding with #1666

**Pull request closed without merging**
