### PR TITLE
fix: cast event.duration to long in event_duration pipeline 

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

The otel span start/end dates are used to compute the event
duration of the APM event, stored as a time.Duration.
The duration is converted to nanoseconds stored in an int64
field, however the values is casted to int in the event_duration
pipeline leading to an overflow if the original 64 bit value
cannot be casted safely to the 32-bit int.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## Related issues

Closes https://github.com/elastic/apm-server/issues/9780

### CODE REVIEW

**Review by marclop — APPROVED** [review]
Looks good, thanks for the quick fix. We should backport to `8.6` as well

**Review by marclop — COMMENTED** [review]
@kruskall can you also add a changelog entry, please?

**Review by lahsivjar — APPROVED** [review]
LGTM other than the changelog entry Marc mentioned earlier.

**Comment by kruskall** [comment]
@marclop Added a changelog. Thanks for metnioning that!

**Review by carsonip — APPROVED** [review]

**Review by marclop — APPROVED** [review]

**Comment by SenthilkumarRasan** [comment]
do we have the above fix backport to 8.4 version?

**Comment by simitt** [comment]
The bug fix will be part of `8.6.0`, there is no further release planned for `8.4`.

**Comment by SenthilkumarRasan** [comment]
is there ETA for 8.6 release? we are waiting on this feature to have proper data from open-telemetry for Jenkins pipelines

**Pull request merged**
