### PR TITLE
Enabled licensed fields/features

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Enable licensed ("x-pack") fields and beater extensions by:
 - generating a separate `x-pack/apm-server/include/fields.go` file from x-pack fields
 - making the `beat.Creator` (i.e. the function signature which `beater.New` adheres to) parameterisable in the root command

Licensed fields are necessary to avoid errors when running with an unlicensed/OSS-only Elasticsearch. The command changes are necessary to enable us to inject additional features which are dependent on these licensed fields, such as https://github.com/elastic/apm-server/pull/3651.

The fields docs (docs/fields.asciidoc) are built from all fields, like in other Beats.

## Checklist
- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [x] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)
- [x] I have rebased my changes on top of the latest master branch
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes
~- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~

## How to test these changes

```
make apm-server apm-server.x-pack
./apm-server --strict.perms=false export template | grep histogram
./x-pack/apm-server/apm-server --strict.perms=false export template | grep histogram
./x-pack/apm-server/apm-server --strict.perms=false export template --es.version=7.5.0 | grep histogram
```

- OSS build should not have any histogram fields.
- x-pack build should have histogram fields with `--es.version` unspecified
- x-pack build should not have histogram fields with `--es-version=7.5.0` specified. ES 7.5.0 does not support histograms; the [libbeat template generator elides fields with the histogram type for ES <7.6.0](https://github.com/elastic/beats/blob/8e9c73b235119fa517d7d8d2577c18ce35a3aafd/libbeat/template/processor.go#L292-L302).

## Related issues

Relates to https://github.com/elastic/apm-server/pull/3651

### CODE REVIEW

**Comment by axw** [comment]
TODO:
 - [ ] Only define the histogram field when using Elasticsearch 7.6.0+

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
Pretty sure the integration tests are just flaky, and not related to this PR.

**Comment by jalvz** [comment]
Is this going to cause any conflict when it comes to syncing the Kibana index pattern?

**Comment by axw** [comment]
> Is this going to cause any conflict when it comes to syncing the Kibana index pattern?

We'll need to use the x-pack binary to generate build/index-pattern.json, but otherwise there should be no change. I'll make this change in a followup.

**Pull request merged**
