### PR TITLE
docs: Anonymous authentication

### PR DESCRIPTION
**Pull request by bmorelli25**
## Motivation/summary

Adds documentation for anonymous authentication for both APM Server standalone and the APM integration.

### Standalone

* New [Anonymous authentication config](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/configuration-anonymous.html)
* Updated [RUM config](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/configuration-rum.html)
* Paragraph in [Secure communication with APM agents](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/secure-communication-agents.html)

### APM integration

* Updated [APM input settings](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/input-apm.html)

### Kibana

* Agent configuration docs updated in https://github.com/elastic/kibana/pull/108285.

## Related issues

Closes https://github.com/elastic/apm-server/issues/5698.
Closes https://github.com/elastic/apm-server/issues/5098.
Closes https://github.com/elastic/observability-docs/issues/917.

### CODE REVIEW

**Comment by bmorelli25** [comment]
I noticed in the `0.4.0` version of the APM integration, I can enable RUM but disable Anonymous Agent access. Is there a use case where someone would want to do that?

Screen Shot 2021-08-11 at 12 59 57 PM

**Comment by axw** [comment]
> I noticed in the 0.4.0 version of the APM integration, I can enable RUM but disable Anonymous Agent access. Is there a use case where someone would want to do that?

Not at the moment. In the future maybe, when https://github.com/elastic/apm-server/issues/1718 is implemented

**Comment by axw** [comment]
Should we create "Unauthenticated communication" as a sibling to "API keys" and "Secret token"? Seems to me it might help discoverability.

image

**Review by axw — COMMENTED** [review]
Content LGTM, thank you. Just wondering whether we should have a dedicated section in the TOC under "Secure communication with APM agents". For reference, Elasticsearch has subsections for each of its auth methods under "User authentication", including anonymous access: https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-up-authentication.html

**Comment by bmorelli25** [comment]
> Just wondering whether we should have a dedicated section in the TOC under "Secure communication with APM agents".

Good idea. Let me play around with it.

**Comment by bmorelli25** [comment]
Found https://github.com/elastic/apm-server/issues/5098 and figured I'd add it into the mix while we're here (deed49d).

**Review by axw — APPROVED** [review]
:heart: thanks, looks great!

**Pull request merged**
