### PR TITLE
updatecli: use the branch for installing go

### PR DESCRIPTION
**Pull request by v1v**
## Motivation/summary

`7.17` and  `main` use a different golang version.

The go setup uses the `main` branch and that's causing some issues when running the updatecli targeting `7.17`.

From now on, all the changes in the `updatecli` should be backported to all the active branches.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## Related issues

Requires https://github.com/elastic/apm-server/pull/12565

### CODE REVIEW

**Comment by v1v** [comment]
This PR is not needed to be backport, changes for GitHub actions are not backported in this particular case

**Review by amannocci — APPROVED** [review]
LGTM

**Comment by v1v** [comment]
For some reason, it uses `go1.21` even though the installed go-version is `1.20`

**Comment by v1v** [comment]
I need to figure out what's going on

**Comment by reakaleek** [comment]
https://github.com/elastic/apm-server/pull/12502/files was the reason why it was using the wrong Go version.

I closed the PR and deleted the branch.
After running the workflow with this branch again the [job](https://github.com/elastic/apm-server/actions/runs/7821064868) succeeded and the newly created [updatecli PR](https://github.com/elastic/apm-server/pull/12615)   worked as expected.

**Review by reakaleek — APPROVED** [review]

**Comment by v1v** [comment]
cla/check

**Pull request merged**
