### PR TITLE
Load dashboards update

### PR DESCRIPTION
**Pull request by makwarth**
- Replaced manual curl command with ./apm-server setup

cc @ruflin @roncohen @simianhacker

### CODE REVIEW

**Comment by ruflin** [comment]
That is definitively the way loading should work in the future. The `setup` commands loads all the dashboards. There is currently one issue with it in apm-server: We use script fields in the index pattern which are not supported by `fields.yml` yet. So if you use setup, it will load the dashboards and generate the index pattern from the apm-server side. This will break some of the dashboards as 2 script fields are missing in the index pattern.

**Comment by makwarth** [comment]
@ruflin Right, but they will be supported in 6.0?

**Comment by ruflin** [comment]
Here is the change that needs to happen first on the beats side: https://github.com/elastic/beats/issues/4899

**Comment by simitt** [comment]
As everything needed is now implemented in `beats` and `apm-server` we could reopen this PR, but the remote branch is already deleted. @makwarth do you still have the local branch? Otherwise I can just create a new one..

**Comment by makwarth** [comment]
Great!

>ruflin deleted the makwarth-patch-1 branch 14 days ago

^ Should I restore the branch @simitt?

**Comment by simitt** [comment]
@makwarth could you please rebase and solve the conflicts?

**Pull request merged**
