### PR TITLE
docs: Secure comms with APM agents

### PR DESCRIPTION
**Pull request by bmorelli25**
### Summary

This is PR 1/2 for the "Secure APM Server" documentation.

This PR updates the following documentation to reflect both the APM Server binary and Fleet-managed APM Server:

- [x] [APM agent TLS communication](https://apm-server_10828.docs-preview.app.elstc.co/guide/en/apm/guide/master/agent-tls.html)
- [x] [API keys](https://apm-server_10828.docs-preview.app.elstc.co/guide/en/apm/guide/master/api-key.html)
- [x] [Secret token](https://apm-server_10828.docs-preview.app.elstc.co/guide/en/apm/guide/master/secret-token.html)
- [x] [Anonymous authentication](https://apm-server_10828.docs-preview.app.elstc.co/guide/en/apm/guide/master/anonymous-auth.html)

This PR also moves the "Secure communication with Logstash" and "Secure communication with Elasticsearch" documentation to their respective "Output config" sections.

**Preview this PR** — see links in the checklist above

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by simitt** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by simitt — APPROVED** [review]

**Pull request merged**
