### PR TITLE
docs: Update field ref with ECS icon

### PR DESCRIPTION
**Pull request by bmorelli25**
## Motivation/summary

I updated `generate_fields_docs.py` in https://github.com/elastic/beats/pull/21359 to include an ECS icon next to ECS fields in the field reference documentation. This PR makes use of that new script to create APM Server's field reference:

* Updates to elastic/beats@fac0347
* Uses `make update` to update the field reference

~Unfortunately, I can't get `make update` to make use of that change. I still have to use a local clone of Beats to get things to work:~

~go mod edit -replace=github.com/elastic/beats/v7=../beats~

~Is this because APM Server needs to update to a later version of Beats before we can make use of this change? If so, does it make more sense to wait on this PR until after that happens?~

## Related issues

Closes elastic/apm#276.
Relates to elastic/beats#20729.

### CODE REVIEW

**Comment by graphaelli** [comment]
> Is this because APM Server needs to update to a later version of Beats before we can make use of this change? If so, does it make more sense to wait on this PR until after that happens?

Sounds right.  You could bundle a `make update-beats` with this pr to test the theory.

**Comment by bmorelli25** [comment]
> Sounds right. You could bundle a make update-beats with this pr to test the theory.

Neat, thanks. That worked!

**Review by axw — APPROVED** [review]
Nice, I like it!

**Comment by bmorelli25** [comment]
It looks like Beats has been updated twice since last night: First in https://github.com/elastic/apm-server/pull/4266, and then again in https://github.com/elastic/apm-server/pull/4267. I will remove that from this PR.

**Pull request merged**
