### PR TITLE
Fleet decode sourcemap response

### PR DESCRIPTION
**Pull request by stuartnelson3**
fixes parsing sourcemaps fetched from fleet

see `resp` in `sourcemap/fleet_store_test.go`, the actual sourcemap is nested under `sourceMap` in the response.

## How to test these changes

- Start apm-server managed by elastic-agent/fleet
- Upload a sourcemap to kibana
- Ingest error events that depend on the uploaded sourcemap

### CODE REVIEW

**Comment by stuartnelson3** [comment]
Error is during step "publish html reports":

```
[2021-07-08T16:43:33.490Z] [htmlpublisher] Archiving at BUILD level /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5635/src/github.com/elastic/apm-server/build/coverage to /var/lib/jenkins/jobs/apm-server/jobs/apm-server-mbp/branches/PR-5635/builds/5/htmlreports/Coverage-Sourcecode-Files

No such DSL method 'cobertura'
```

**Review by simitt — APPROVED** [review]

**Comment by stuartnelson3** [comment]
Waiting to test this with @cauemarcondes, will merge when we confirm it works for him

**Review by cauemarcondes — APPROVED** [review]
LGTM.

I tested locally with @stuartnelson3 `s docker images.

Before uploading the source map:
Screen Shot 2021-07-09 at 12 34 19

After uploading source map:
Screen Shot 2021-07-09 at 12 32 43

**Pull request merged**
