### PR TITLE
String source map

### PR DESCRIPTION
**Pull request by roncohen**
Based on @simitt's PR https://github.com/elastic/apm-server/pull/432 but updated to store as string.

### CODE REVIEW

**Comment by simitt** [comment]
@roncohen could run `make update` please so the `NOTICE` changes accordingly.

**Comment by roncohen** [comment]
@simitt done

**Comment by simitt** [comment]
@roncohen what do you think about this https://github.com/elastic/apm-server/pull/432/files#r159254075?

**Comment by simitt** [comment]
After several discussions and changes in beats I think we should upload the information as a base64 encoded string, stored as binary in ES, as it is done by PR #432 and close this one.

**Pull request merged**
