### PR TITLE
index the url path only of the sourcemaps

### PR DESCRIPTION
**Pull request by jalvz**
fixes https://github.com/elastic/apm-server/issues/1649

this is the best i came up with, as wildcard queries are slow in elasticsearch (particularly if the wildcard is at the beginning, like in here) and caching would be quite complicated too

- needs changelog

### CODE REVIEW

**Comment by jalvz** [comment]
in that case the services would be different, so they wouldn't match, right? is there a realistic case for same service, version and url path, but different hostname?

if so, i also could also add a boost to the full url query term and sort by relevance. either case for me it feels like overdoing it, but i dont know.

**Comment by simitt** [comment]
The implementation LGTM, thanks for taking care of this @jalvz ! 
From a use-case point of view, I am not sure if this can cause troubles, @jahtalab could you give this change a thought from a users perspective?

**Comment by jahtalab** [comment]
Just had a zoom call with @jalvz , decided to consider searching for an exact match first and if that fails to search for only the path part!

**Comment by jalvz** [comment]
thanks @jahtalab! 
The straightforward way would be 6401bb8ace79d6e0d07740411c4f57025cb6bd7b, but we could investigate other alternatives indeed.

**Comment by jalvz** [comment]
jenkins retest this please

**Comment by jalvz** [comment]
jenkins retest this, please

**Comment by jalvz** [comment]
jenkins retest this, please

**Pull request merged**
