### PR TITLE
[6.x] Refactor Event creation and enhancer utility method. (#673)

### PR DESCRIPTION
**Pull request by simitt**
Backports the following commits to 6.x:
 - Refactor Event creation and enhancer utility method.  (#673)

### CODE REVIEW

**Comment by simitt** [comment]
jenkins, retest this please

**Comment by simitt** [comment]
jenkins, retest this please

**Comment by simitt** [comment]
jenkins, retest this please

**Comment by jalvz** [comment]
jenkins, retest it please

**Comment by jalvz** [comment]
jenkins retest this please

**Pull request merged**
