### PR TITLE
[tests] Fix geoip resolved testdata

### PR DESCRIPTION
**Pull request by simitt**
Adapt tests for data resolved with geoip processor, after upgrade
of the geolite2 database in elasticsearch
(https://github.com/elastic/elasticsearch/pull/49308)

### CODE REVIEW

**Comment by simitt** [comment]
Agent config management tests are still failing, but this PR fixes the two failing tests related to GeoIP processor.

**Comment by jalvz** [comment]
> Agent config management tests are still failing

Why is that?

**Comment by simitt** [comment]
> Agent config management tests are still failing
>> Why is that?

Yesterday some tests on master started failing. Looking into it there are two kinds of failing tests: agent config management and geoIP processed data. This PR fixes the geoIP data. 
The failing agent config management tests are completely unrelated from this PR. IMO their failing might be a timing issue, but should be discussed separately.

**Comment by jalvz** [comment]
ill have a look to the failing ones, thanks.

**Pull request merged**
