### PR TITLE
Update architecture to new ES output handling

### PR DESCRIPTION
**Pull request by simitt**
## Motivation/summary
Reflect the new ES output handling in the architecture diagram.

### CODE REVIEW

**Review by axw — APPROVED** [review]
LGTM. Do you want to include libbeat still for other outputs?

**Comment by simitt** [comment]
I can if you prefer to, but not certain we should highlight it as long as it is only supported by the standalone binary.

**Comment by axw** [comment]
Good point, let's leave it out for now.

**Review by marclop — COMMENTED** [review]
We did remove the jaeger dedicated listeners from 8.0 correct? Should we update the diagram to show that they're only available up to 7.16?

**Review by marclop — APPROVED** [review]

**Pull request merged**
