### PR TITLE
Switch to JSON logging by default

### PR DESCRIPTION
**Pull request by simitt**
## Motivation/summary
This PR changes the default for `logging.json=true`.

With https://github.com/elastic/apm-server/pull/3829 we switched to ECS compliant logging by default. Since the [ecs-logging-go-zap](https://github.com/elastic/ecs-logging-go-zap) is built on top of the JSON formatter, using it only makes sense in combination with logging in JSON. 

We should consider this a bugfix for an unreleased bug and backport to `7.11`. 

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
~- [ ] Documentation has been updated~

## How to test these changes
Start APM Server and observe logs are in JSON format by default. 

## Related issues
related to #3796

### CODE REVIEW

**Review by jalvz — APPROVED** [review]
I don't have a strong opinion, but this doesn't look like a bug fix to me

**Comment by axw** [comment]
I think it's reasonable to consider this a bug, seeing as the original change won't work according to user expectations without this fix.

**Comment by simitt** [comment]
Thanks @axw and @jalvz. As described above:
> We should consider this a bugfix for an unreleased bug and backport to 7.11.

I added it as point in the _Change_ section, as I consider it a bugfix for #3829 which will be also released with `7.11`.

**Comment by jalvz** [comment]
Simply started with and without `-E logging.json=false`, it works as expected

**Pull request merged**
