### PR TITLE
Show transaction.result in Requests per Minute vis.

### LINKED ISSUE #214: Request Per Minute [APM] visualization uses wrong field
Request Per Minute [APM] should use transaction.result as the filter field for the status code (or APM is sending the wrong field ;) )

### PR DESCRIPTION
**Pull request by simitt**
Do not group by filters, but show all values grouped by terms.

This fixes #214.
Needs some discussion if this is the preferred way for visualization.

### CODE REVIEW

**Comment by simitt** [comment]
@makwarth , @vanjacosic , @formgeist could you have a look if the dashboard change is fine with you?
@simianhacker cc

**Comment by formgeist** [comment]
Didn't get around to look at this today, but will on Monday 👍

**Comment by simitt** [comment]
@ruflin could you have a look at those changes and merge as just discussed.

**Comment by ruflin** [comment]
Quickly tested it on 5.6 and didn't see any errors. We can further keep iterating on the dashboards.

**Pull request merged**
