### PR TITLE
[7.10] fix: set default value for ONLY_DOCS env var (#4395)

### PR DESCRIPTION
**Pull request by kuisathaverat**
Backports the following commits to 7.10:
 - fix: set default value for ONLY_DOCS env var (#4395)

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by simitt — APPROVED** [review]

**Comment by simitt** [comment]
Jenkins, run the package tests

**Comment by simitt** [comment]
Jenkins, run the package tests please

**Comment by kuisathaverat** [comment]
package test

**Comment by kuisathaverat** [comment]
Jenkins run the package tests

**Comment by kuisathaverat** [comment]
ok, it can not trigger the package because 7.10 branch does not manage the GitHub comment for packages https://github.com/elastic/apm-server/blob/d36bac1f96166b7f37fb58dedf2fce4f77119ade/Jenkinsfile#L28

**Pull request merged**
