### PR TITLE
sampling: add missing license check

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Tail-based sampling will be a licensed feature, add code to enforce it.

We also introduce support for running ephemeral Elasticsearch containers using testcontainers-go. This is used for running a Basic-licensed Elasticsearch without modifying the docker-compose services, which is destructive and may interfere with other tests or general docker-compose usage.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
~- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~

I have considered changes for:
~- [ ] documentation~
- [x] logging (add log lines, choose appropriate log selector, etc.)
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))~
- [x] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
~- [ ] telemetry~
~- [ ] Elasticsearch Service (https://cloud.elastic.co)~
~- [ ] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)~
~- [ ] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)~

## How to test these changes

1. Run Elasticsearch with a trial license
2. Enable tail-based sampling -- it should work
3. Update Elasticsearch with a Basic license (https://www.elastic.co/guide/en/elasticsearch/reference/current/start-basic.html)
4. The server should stop working, and start logging licensing errors

## Related issues

https://github.com/elastic/apm-server/issues/4185

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

**Review by jalvz — APPROVED** [review]

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
The new test is a bit unreliable, I'm looking into it.

**Comment by axw** [comment]
The latest test failure is unrelated, and will be addressed by https://github.com/elastic/apm-server/pull/4353

**Comment by simitt** [comment]
Tested with BC 1 with the suggested steps.
The APM Server starts logging license notes as expected
```
{"log.level":"info","@timestamp":"2020-12-23T16:02:37.422+0100","log.logger":"license","log.origin":{"file.name":"licenser/es_callback.go","file.line":51},"message":"Elasticsearch license: Basic","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2020-12-23T16:02:37.437+0100","log.logger":"license","log.origin":{"file.name":"apm-server/main.go","file.line":102},"message":"Checking license for tail-based sampling","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2020-12-23T16:02:37.437+0100","log.logger":"license","log.origin":{"file.name":"licenser/check.go","file.line":35},"message":"License is active for Platinum","ecs.version":"1.6.0"}
```

Two observations:
* When sending intake requests to the server it still responds with `202` until the queue is filled up. 
* Other events such as `error` or `metric` events also stop being ingested.
* 
@axw - I assume that's ok but haven't realized this earlier.

**Comment by axw** [comment]
@simitt It's just a backstop, so I think this somewhat awkward behaviour is OK.

**Pull request merged**
