### PR TITLE
Move Jenkinsfile under .ci

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Tidying up the repo.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

N/A

## Related issues

None

### CODE REVIEW

**Review by lahsivjar — APPROVED** [review]

**Review by v1v — COMMENTED** [review]
If we do so, there will be some side effects:
1) Old tags will not be shown. Nothing we can do about it, but wait for the new tags
2) Old branches will not be shown unless this change is backported.


Other than that, LGTM

**Comment by axw** [comment]
Chatted with @v1v on Slack: tags is not an issue, they're not available anyway; 7.17 and 8.3 are active branches, so I'll backport to those.

**Comment by axw** [comment]
@v1v apm-ci/pr-merge isn't starting. Is there some chicken-and-egg situation here, with the job definition and Jenkinsfile location changing? Should I just merge?

**Comment by v1v** [comment]
>  @v1v apm-ci/pr-merge isn't starting. Is there some chicken-and-egg situation here, with the job definition and Jenkinsfile location changing? Should I just merge?


Yes, 🐔 🥚 , so feel free to merge it

**Comment by v1v** [comment]
@mergifyio backport 7.16

**Comment by v1v** [comment]
@mergifyio backport 8.0

**Comment by v1v** [comment]
@mergifyio backport 8.1

**Comment by v1v** [comment]
@mergifyio backport 8.2

**Pull request merged**
