### PR TITLE
fix: do not stop sampling processor when failing to delete trace events

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

The sampling processor should never stop when apm-server is running. Instead log an error on Warn level and skip the current event.

Handle `ErrTxnTooBig` error when deleting trace events: because deleting adds a transaction it can increase the size above the limit. 
Flush the events before deleting.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## Related issues

Closes https://github.com/elastic/apm-server/issues/12053

### CODE REVIEW

**Comment by simitt** [comment]
From the issue description:
>To fix this we need to

>already reject events that exceed a max size when they are received, as well as ensuring that events of allowed size can be processed by the system

This PR addresses the part of the github issue to not stop the TBS processor, but it does not address the problem that events exceeding the max size fill up storage without ever getting deleted. Events that are too large to be deleted, should be rejected already when received.

**Comment by carsonip** [comment]
> already reject events that exceed a max size when they are received

There is the same `ErrTxnTooBig` check in `writeEntry`. Did the deletion txn get too large because writes are batched? Should we handle the ErrTxnTooBig thrown by flushing and retrying?

**Comment by simitt** [comment]
>There is the same ErrTxnTooBig check in writeEntry, so we should already be doing it.

The [code](https://github.com/elastic/apm-server/blob/main/x-pack/apm-server/sampling/eventstorage/storage.go#L217-L225) ensures that an event is added to a new transaction if the max size of the write transaction would otherwise be exceeded. I overlooked that the event cannot be stored in the first place if the event itself is exceeding the max transaction size. 

>Did the deletion txn get too large because writes are batched? Should we handle the ErrTxnTooBig thrown by flushing and retrying?

Yes, that sounds like the only reason why this might fail. +1 on the suggested solution.

**Comment by carsonip** [comment]
> I'm not sure what this means, can you elaborate ?

`DeleteTraceEvent` and `WriteTraceEvent` share the same `rw`. Imagine processor calls `WriteTraceEvent` multiple times right before reaching `ErrTxnTooBig`, then calls `DeleteTraceEvent`, which takes the txn right over the txn size limit. Since there is no `ErrTxnTooBig` handling inside `DeleteTraceEvent` unlike `writeEntry`, it will throw an error. I suspect this is the root cause.

To fix it, handle `ErrTxnTooBig` gracefully in `DeleteTraceEvent` like what we have in `writeEntry`

**Review by carsonip — APPROVED** [review]
lgtm

- Can you update the PR description?
- Do we want to backport this to 8.12, i.e. 8.12.2?

**Comment by carsonip** [comment]
## Testing notes

:heavy_check_mark: test-plan-ok

Tested via https://github.com/elastic/apm-server/pull/12688 as it is almost impossible to manually test this behavior. Test in #12688 fails without the handling in this PR.

**Pull request merged**
