### PR TITLE
Remove the service from the dataset for all events except application metrics

### PR DESCRIPTION
**Pull request by jalvz**
## Motivation/summary

As stated in https://github.com/elastic/apm-server/issues/5445

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

## How to test these changes

Ingest data with data streams enabled (via Fleet integration), and observe that only application metrics include the service name in the dataset.

## Related issues

Closes https://github.com/elastic/apm-server/issues/5445

### CODE REVIEW

**Review by axw — APPROVED** [review]
LGTM, thanks!

**Comment by axw** [comment]
jenkins run the tests please

**Comment by jalvz** [comment]
@bmorelli25 you probably want to update some docs about this (service name no longer part of dataset part in the index names for all event types except application metrics)

**Comment by axw** [comment]
Tested with 7.14.0-BC1, looks good.

image

image

**Pull request merged**
