### PR TITLE
set more config defaults in code

### PR DESCRIPTION
**Pull request by graphaelli**
Following up on our discussion of setting defaults in code to match the configuration file.  I'm still not sure if this is appropriate for a minor release, happy to discuss.

### CODE REVIEW

**Comment by graphaelli** [comment]
This leaves just `output.elasticsearch` - that one is more tricky, I'm working on it.

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by roncohen** [comment]
we probably need a change log entry to make people aware.

**Comment by graphaelli** [comment]
Sounds good, I'll add that and get this merged in.

**Pull request merged**
