### PR TITLE
docs: link to APM Attacher docs

### PR DESCRIPTION
**Pull request by bmorelli25**
### Summary

This PR is a follow-up to https://github.com/elastic/apm-server/pull/9246. It adds links to the new APM attacher book and removes a reference to the Helm chart.

Blocked by https://github.com/elastic/apm-mutating-webhook/pull/64

### CODE REVIEW

**Comment by bmorelli25** [comment]
\test

**Review by simitt — APPROVED** [review]

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
