### PR TITLE
Disable Google cache after object upload

### PR DESCRIPTION
**Pull request by cachedout**
## Motivation/summary

Attempt to fix failure in branch packaging test

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## Related issues

Refs issue in private repo.

### CODE REVIEW

**Review by v1v — COMMENTED** [review]
IIRC, we don't manage the google storage bucket defined in the `JOB_GCS_BUCKET` credentials but infra.

What's the current issue? In case, it can be solved in the bucket itself?

**Comment by cachedout** [comment]
> What's the current issue? In case, it can be solved in the bucket itself?

Thanks for the question, @v1v 

What's happening here is that when we upload the artifact, Google caches it for 3600s by default. This means that we upload a new hash for the artifact but when we try to download it, we get the previous copy. This then breaks the packaging test because beats-tester fails to get the correct hash.

There were two previous attempts to fix this issue, neither of which were successful:

https://github.com/elastic/beats-tester/pull/204
https://github.com/elastic/beats-tester/pull/205

So the idea here is to upload the artifact and then immediately adjust the meta-data. I did investigate whether or not it is possible to set this on a per-bucket layer and it is not. We could do it at upload-time, but the strategy of using a second-call as this PR does seems to only add minimal overhead.

**Comment by v1v** [comment]
Thanks for the clarification.
There is something that I'm confused, https://github.com/elastic/apm-server/pull/4401 was implemented to support the `commit-id` folder name rather than the `latest` folder name. The idea was to avoid testing the `beats-tester` pipeline when the latest artifacts were uploaded from the `apm-server` by another build, a concurrent issue.

Maybe there is a missing configuration somewhere that somehow is not well implemented? Otherwise, the cache issue should not happen since the `commit-id` is unique.

**Comment by v1v** [comment]
To illustrate the above, I've just looked at:

- https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/1159/ that triggered the beats-tester build -> https://apm-ci.elastic.co/job/apm-server/job/apm-server-check-packages-mbp/job/master/757/

And the `beats-tester.properties` file is read in https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-check-packages-mbp/detail/master/757/pipeline/27#step-31-log-1.

image

And the content can be seen in 

https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/1159/artifact/beats-tester.properties/*view*/

Definitely there is something missing since the `APM_URL_BASE` is not correct 

Though

**Comment by cachedout** [comment]
Could we be falling back here? 

https://github.com/elastic/apm-server/pull/4401/files#diff-62bc844eece79c6e6233131c5452490b5d38b86764b592ed4ec4e764f0547c28R53

**Comment by v1v** [comment]
There was a bug in the current implementation, since the global environment variables map is immutable :/ . https://github.com/elastic/apm-server/pull/6012 should help with this, 🤞

**Comment by cachedout** [comment]
Ah, nice. OK, let's try that. I'll close this in the meantime.

**Pull request closed without merging**
