### PR TITLE
Universal Profiling: Improved RPC protocol and code sync

### PR DESCRIPTION
**Pull request by christos68k**
### Summary

Major changes include improvements to RPC protocol (per-trace-event second-resolution timestamps, traffic reduction) and code synchronization with pf-elastic-collector.

The following must be reviewed (rough order of priority):

1. Executable/leaf frame queues and all operations related to symbolization. Besides looking at the code, these need to be tested as they haven't been tested by me. See below for notes on testing.
2. ILM. I haven't made any changes/additions here.
3. Dependencies/versions. I merged a [previous](#10647) PR to update `go-elasticsearch` to 8.7.  The executable/leaf frame queues are using `simplelru` [v0.3.1](https://github.com/hnlq715/golang-lru/releases/tag/v0.3.1), which includes our time expiration fixes.
5. The rest of the code, paying extra attention to bits that you think I might have missed.

Do keep in mind that this PR is the result of -mostly- manual code porting, due to differences between the two trees that forbid automated code synchronization, which results in higher probability of me introducing errors/omissions. I have tested basic operation with a current HA.

In order to build an APM server and test locally, follow [these](https://github.com/elastic/prodfiler/blob/main/docs/elastic-profiling-local-development.md) instructions step-by-step, including the setup via `utils/elastic-profiling`. You won't be able to do the initial UP setup via Kibana (it will error with a message saying it needs Cloud) but once you have HA running and sending data, that Kibana dialog will disappear.

@axw : I tagged you because there are some minor changes to `x-pack/apm-server/main.go` you might want to look at. Feel free to skip the rest.

- Updated generated protobuf definitions
- Updated CollectTracesAndFrames / CollectTracesAndCounts
- Updated CollectFrameMetadata
- Added common/encodebody{_test}.go
- Updated auth handler
- Updated libpf
- Updated metrics.json
- Updated basehash
- Updated common
- Added github.com/goccy/go-json dependency
- Updated logging to be consistent across RPC receivers
- Updated profiling systemtest
- Added executable/leaf frame queues. I skipped the tests as they're implemented in time-dependent fashion and can result in false negatives.
- Dropped writing the StackTraceEvent/host.ipstring field (KQL auto-suggestion for IP fields has been fixed)

### CODE REVIEW

**Comment by rockdaboot** [comment]
There are several changes missing, e.g. this PR still uses the MPL'ed simpleLRU.
So it looks like there where several changes (mostly refactorings), that weren't tagged `port-to-apm`. In a first step, I'll go through the code to *only* find possible functionality changes.

**Review by rockdaboot — APPROVED** [review]
:+1:
Tested locally incl. running the symbolizer on top of it. The symbols for native frames (e.g. libc.so, libxul.so) appear in Universal Profiling.

**Comment by christos68k** [comment]
> Then there where some refactorings, that weren't tagged `port-to-apm` in prodfiler. As far as I can tell, these don't affect functionality. And it is possibly not worth to sync the code when we aim for a stand-alone collector outside of apm-server for release 8.9.

For the freelru changes, I'd wait for 8.8.1, I wouldn't like to do them last-minute and IIRC they also involve some dependencies that the rest of apm-server is using that have been updated.

> I added a change from today (dropping host.ipstring from StackTraceEvent).

Thanks!

**Review by inge4pres — APPROVED** [review]
LGTM! 
Great work @christos68k thanks 🙏🏼 
I tested specifically the protocol compatibility and everything works as intended.

**Comment by rockdaboot** [comment]
> For the freelru changes, I'd wait for 8.8.1, I wouldn't like to do them last-minute and IIRC they also involve some dependencies that the rest of apm-server is using that have been updated.

I am fine with that. Just want to mention that using go-freelru does not add any external dependencies while simplelru does ! (looking at the go.mod changes of this PR)

The `go.mod` file from go-freelru:
```
module github.com/elastic/go-freelru

go 1.18
```

But maybe I misunderstand you and you refer to something else !?

**Review by axw — APPROVED** [review]

**Comment by christos68k** [comment]
> The `go.mod` file from go-freelru:
> 
> ```
> module github.com/elastic/go-freelru
> 
> go 1.18
> ```
> 
> But maybe I misunderstand you and you refer to something else !?

It's not just go-freelru, but all the changes associated with it in our repo, which result in the following additions to `go.mod`:

```diff
+	github.com/klauspost/cpuid/v2 v2.2.4 // indirect
+	github.com/zeebo/xxh3 v1.0.2 // indirect
+	golang.org/x/sys v0.7.0 // indirect
```

**Comment by rockdaboot** [comment]
> > The `go.mod` file from go-freelru:
> > ```
> > module github.com/elastic/go-freelru
> > 
> > go 1.18
> > ```
> > 
> > But maybe I misunderstand you and you refer to something else !?
> 
> It's not just `go-freelru`, but all the changes associated with it in our repo, which result in the following additions to `go.mod`:
> 
> ```diff
> +	github.com/klauspost/cpuid/v2 v2.2.4 // indirect
> +	github.com/zeebo/xxh3 v1.0.2 // indirect
> +	golang.org/x/sys v0.7.0 // indirect
> ```

I mostly concerned about
```
+	github.com/hnlq715/golang-lru v0.3.1 // indirect
```
which IMO comes from this import in `x-pack/apm-server/profiling/queue.go`
```
lru "github.com/hnlq715/golang-lru/simplelru"
```
We surely can address that after FF.

**Pull request merged**
