### PR TITLE
Record plaintext stack traces as error.stack_trace

### LINKED ISSUE #7154: OpenTelemetry: store `exception.stacktrace` as `error.stack_trace` if it cannot be parsed
See https://github.com/elastic/kibana/issues/124204

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Add the `error.stack_trace` field to the `error_logs` data stream, and change our OpenTelemetry processing to record unparsed stack traces as `error.stack_trace` rather than `error.exception.attributes.stacktrace`.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [x] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
~- [ ] Documentation has been updated~

## How to test these changes

1. Send a OTLP span with an exception that has a stack trace, using a non-Java SDK
2. Check that an error document is indexed, and the stack trace is recorded in `error.stack_trace`
3. Check that `error.stack_trace` is searchable

## Related issues

Closes #7154

### CODE REVIEW

**Review by marclop — APPROVED** [review]

**Comment by scbjans** [comment]
Would it be possible to backport this to 8.2.x branch?

**Comment by simitt** [comment]
@scbjans unfortunately this enhancement didn't make it into `8.2.0` and we aim for only backporting bug fixes to patch versions. It is planned to be available with `8.3.0`.

**Comment by butlerx** [comment]
Will this be back ported to 7.x where the issue also exists?

**Comment by axw** [comment]
@butlerx 7.x is in maintenance mode and will only receive bug fixes - not enhancements such as this.

**Pull request merged**
