### PR TITLE
accept application/json; charset=UTF-8 as contentType in the request

### LINKED ISSUE #676: client-side endpoint: setting `Content-Type` header to "application/json; charset=UTF-8" results in 400: Bad Request
Setting `Content-Type` header to "application/json; charset=UTF-8" results in 400: Bad Request

Response: "while decoding: invalid content type: application/json; charset=UTF-8"

`charset` is part of the [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type), apm-server should accept that.

### PR DESCRIPTION
**Pull request by jalvz**
Fixes #676

### CODE REVIEW

**Comment by jalvz** [comment]
@jahtalab

**Comment by jahtalab** [comment]
Thanks for the quick fix @jalvz 👍 !

**Comment by jahtalab** [comment]
Should we backport this?

**Comment by jalvz** [comment]
yes, and add a changelog entry too :)

**Comment by jalvz** [comment]
@simitt can you have a quick look at e5c718f57fabf4bf9fd2bcd6d970e0025b73c7aa to check that i got right the 6.2 release cut?
6.2: https://github.com/elastic/apm-server/compare/71df0d96445df35afe27f38bcf734a0828e0761d...4daa36bd5c144cf9182afc62dc8042af663756c6

6.x: https://github.com/elastic/apm-server/compare/4daa36bd5c144cf9182afc62dc8042af663756c6...master

**Pull request merged**
