### PR TITLE
document how ratelimit client.ip is derived

### LINKED ISSUE #6153: Document client.ip derivation its use in anonymous auth rate-limiting
We should document:
 - How `client.ip` is derived. i.e. Which headers, such as X-Forwarded-For, are used.
 - That `client.ip`is used in rate limiting for anonymous auth, e.g. for RUM.

This is important for users configuring their own load balancers/reverse proxies.

### PR DESCRIPTION
**Pull request by stuartnelson3**
## Motivation/summary

document how `client.ip` is derived for ratelimiting anonymous events

## Checklist

~~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~~
- [x] Documentation has been updated

## How to test these changes

non-functional change

## Related issues

closes #6153

### CODE REVIEW

**Comment by stuartnelson3** [comment]
If this should be written somewhere else let me know

**Review by axw — COMMENTED** [review]
Looks good, but this config is deprecated in 7.15 and replaced by https://apm-server_6162.docs-preview.app.elstc.co/guide/en/apm/server/master/configuration-anonymous.html#config-auth-anon-ip-limit. Can you please move it there?

**Review by axw — APPROVED** [review]
thank you!

**Pull request merged**
