### PR TITLE
bump version 8.2

### PR DESCRIPTION
**Pull request by stuartnelson3**
TODO:

`make update-beats`
~~update go-elasticsearch~~ skipping for now, updating is resulting in an alpha build?

```
# go get github.com/elastic/go-elasticsearch/v8@8.0
go: downloading github.com/elastic/go-elasticsearch/v8 v8.0.0-alpha.0.20220127111727-5269e7e57568
go: downloading github.com/elastic/elastic-transport-go/v8 v8.0.0-alpha
go get: added github.com/elastic/elastic-transport-go/v8 v8.0.0-alpha
go get: upgraded github.com/elastic/go-elasticsearch/v8 v8.0.0-20210727161915-8cf93274b968 => v8.0.0-alpha.0.20220127111727-5269e7e57568
```

### CODE REVIEW

**Review by simitt — COMMENTED** [review]
Beats has not yet updated the version to `8.2` (https://github.com/elastic/beats/blob/master/libbeat/version/version.go), so we will have to pull again; but this is fine to merge for now. 

The update to `go-elasticsearch` will result in some strange `alpha` name (similar as it does for beats), as it is pointing to unreleased versions.

**Comment by axw** [comment]
Because we don't yet have 8.2.0-SNAPSHOT images, apm-integration-testing is running with 8.1.0-SNAPSHOT. Thus, the tests fail to install the 8.2.0-dev1 integration package, and the ingest pipeline blocks all ingestion from apm-server 8.2.

We can't get the integration tests to pass until we have 8.2.0-SNAPSHOT images, so I'll merge this and we can fix any legitimate integration test failures later.

**Pull request merged**
