### PR TITLE
Remove ingest pipeline registration

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Remove ingest pipeline registration/configuration. Also, stop blocking indexing of logs when data streams are disabled. Along with the removal of explicitly named pipelines, this allows us to simplify the publisher package.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
~- [ ] Documentation has been updated~ Docs will need to be overhauled, I'll leave this for now

## How to test these changes

N/A, removing functionality only.

## Related issues

https://github.com/elastic/apm-server/issues/5961

### CODE REVIEW

**Review by marclop — APPROVED** [review]
🎉

**Comment by axw** [comment]
Ugh, looks like this breaks integration tests. We were going to have to update them for the followup anyway, so I guess I'm doing that now instead.

**Pull request merged**
