### PR TITLE
Removed `observer.version_major`

### LINKED ISSUE #7387: Stop recording `observer.version_major`
The field `observer.version_major` is non-standard, and existed only for the UI to filter out legacy (<7.0) docs. This check is no longer performed, so we can stop setting the field: https://github.com/elastic/kibana/issues/125621

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Motivation/summary
Fixes #7387

## Checklist
- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [x] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [x] Documentation has been updated

### CODE REVIEW

**Comment by marclop** [comment]
run elasticsearch-ci/docs

**Review by axw — APPROVED** [review]
LGTM, thank you!

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
