### PR TITLE
packaging/docker: vendor Mozilla CA certificates

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Vendor CA certificates and add to the Docker image. The certificate bundle was fetched from Fetched from https://curl.se/ca/cacert-2023-05-30.pem; see also https://curl.se/docs/caextract.html.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

See https://github.com/elastic/apm-server/issues/10332

## Related issues

Closes https://github.com/elastic/apm-server/issues/10332

### CODE REVIEW

**Review by marclop — APPROVED** [review]
should this also be back ported to 8.8?

**Comment by axw** [comment]
> should this also be back ported to 8.8?

yes, good call

**Comment by carsonip** [comment]
test-plan-ok

Testing notes:
- Tested with 8.8.2 BC1 docker image.
- Confirmed preconditions passed with
```
{"log.level":"info","@timestamp":"2023-06-23T14:59:40.943Z","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":68},"message":"no longer blocking ingestion as all precondition checks are now satisfied","service.name":"apm-server","ecs.version":"1.6.0"}
```

On the other hand I reproduced this with the same setup with 8.8.1 docker image to confirm that behavior changed:
```
{"log.level":"error","@timestamp":"2023-06-23T15:01:47.080Z","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":64},"message":"precondition failed: x509: certificate signed by unknown authority","service.name":"apm-server","ecs.version":"1.6.0"}
```

**Comment by reydelleon-skuvault** [comment]
@carsonip When is this expected to make it out to a published image? I'm experiencing this issue with 8.8.1 (latest published image as of now) as you just showed in your previous comment.

**Comment by carsonip** [comment]
@reydelleon-skuvault The fix will be in 8.8.2. Keep an eye on new releases as it should come out soon.

**Comment by reydelleon-skuvault** [comment]
Awesome! Thanks!

**Pull request merged**
