### PR TITLE
include build time and revision in version information

### PR DESCRIPTION
**Pull request by graphaelli**
for #375, results in:

```
2017/12/12 17:17:28.047058 beat.go:203: INFO Setup Beat: apm-server; Version: 7.0.0-alpha1 [6819aa06a0ed7ecc18f9bb7291d65b1ca50917fd built 2017-12-12T17:14:46]
```

Hook up to HTTP in #395 can happen after this is in.

*note*: this does add a make warning:
```
_beats/libbeat/scripts/Makefile:92: warning: ignoring old commands for target `apm-server'
```
I'm investigating whether we can get support upstream for `GOBUILD_FLAGS` or similar

### CODE REVIEW

**Comment by graphaelli** [comment]
opened elastic/beats#5871

**Comment by graphaelli** [comment]
@simitt elastic/beats#5871 was merged really quickly - pulled in the beats update here and eliminated the make warning - can you take another look since this changed so much since the initial review?

**Comment by ruflin** [comment]
@andrewkroh I wonder if we should add this as part of libbeat especially with https://github.com/elastic/beats/issues/5946 in mind?

**Comment by andrewkroh** [comment]
Yes, I think we should have this in libbeat so that it becomes part of every Beat. I'd really like to have this available info in the logs and with `-version`.

**Comment by ruflin** [comment]
@graphaelli Interested to contribute this back to beats?

**Comment by graphaelli** [comment]
@ruflin sure, on it.

**Comment by graphaelli** [comment]
elastic/beats#5973 opened for that @andrewkroh / @ruflin

**Pull request merged**
