### PR TITLE
build: bump go-docappender for heap usage fix

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

Attempt to fix the increased memory usage in benchmarks

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by marclop** [comment]
@kruskall if you re-open the PR in the elastic owned repo, you can trigger the benchmarks for this change.

**Comment by kruskall** [comment]
The fix is in go-docappender, I have no idea why I bumped apm-data :facepalm:

**Review by carsonip — APPROVED** [review]

**Comment by kruskall** [comment]
I pushed upstream, created a new branch and run the benchmarks. It seems the issue is fixed and heap usage decreased.

**Comment by kruskall** [comment]
https://github.com/elastic/apm-server/actions/runs/5647158766

**Pull request merged**
