### PR TITLE
docs: fix typo in 6.1 doc page header

### PR DESCRIPTION
**Pull request by watson**
I hope this is the correct approach for fixing something directly on a version branch

### CODE REVIEW

**Comment by jalvz** [comment]
I believe it has to be fixed in master and then backported? (in case is also wrong in master, ofc)

**Comment by simitt** [comment]
@jalvz generally yes, but the docs headers are removed in master, so I'd say this is the proper approach to fix it.

**Comment by jalvz** [comment]
ok, cool. i just `grep`ed "an beta release" in master and showed 42 occurrences, so something is wrong somewhere, but i have no idea of how docs are generated.

**Comment by watson** [comment]
@jalvz that's probably from your local `build` directory - which is not checked into git. So it's just the result of building the docs for version 6.1 I think

**Comment by jalvz** [comment]
Yes, you are right, sorry for the noise. I was actually confused because `make docs` doesn't remove the `build` folder, so i had the wrong stuff locally.

**Pull request merged**
