### PR TITLE
[apmpackage] Add TBS enabled config option

### PR DESCRIPTION
**Pull request by simitt**
## Motivation/summary
Introduce dedicated field for tailbased sampling enabled to ease work on the APM UI editor side. 

## How To Test this
Needs to be tested in combination with the UI work when enabling tail based sampling via the APM Integration editor. Ensure TBS is disabled by default, and can be enabled and disabled based on a bool slider in the UI. 

## Related issues
related https://github.com/elastic/kibana/issues/121534

### CODE REVIEW

**Comment by simitt** [comment]
Failing test seems related to general setup, but not the apm package changes introduced with this PR
```
[2022-01-24T09:29:58.571+00:00][INFO ][http.server.Kibana] http server running at http://0.0.0.0:5601
[2022-01-24T09:29:58.694+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-01-24T09:29:58.706+00:00][INFO ][plugins.securitySolution] Dependent plugin setup complete - Starting ManifestTask
[2022-01-24T09:30:00.112+00:00][INFO ][status] Kibana is now available (was degraded)
[2022-01-24T09:30:06.101+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-01-24T09:30:06.302+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-01-24T09:30:06.319+00:00][INFO ][plugins.fleet] Beginning fleet setup
[2022-01-24T09:30:06.501+00:00][INFO ][plugins.fleet] Fleet setup completed
[2022-01-24T09:30:24.208+00:00][INFO ][plugins.apm] Deleting config systemtest_service/undefined (32lli34BJ46bIqe8vJbw)
[2022-01-24T09:30:24.318+00:00][INFO ][plugins.apm] Updated Fleet integration policy for APM to remove the deleted agent configuration.
[2022-01-24T09:30:24.371+00:00][INFO ][plugins.apm] Deleting config systemtest_service/testing (bWlli34BJ46bIqe825eu)
[2022-01-24T09:30:26.185+00:00][INFO ][plugins.apm] Updated Fleet integration policy for APM to remove the deleted agent configuration.
[2022-01-24T09:30:49.624+00:00][INFO ][plugins.apm] Creating config systemtest_service/undefined
[2022-01-24T09:30:52.540+00:00][INFO ][plugins.fleet] Package policy upgraded successfully
[2022-01-24T09:30:52.540+00:00][INFO ][plugins.apm] Saved latest agent settings to Fleet integration policy for APM.
[2022-01-24T09:30:58.125+00:00][INFO ][plugins.apm] Creating config systemtest_service/testing
[2022-01-24T09:31:00.601+00:00][INFO ][plugins.fleet] Package policy upgraded successfully
[2022-01-24T09:31:00.601+00:00][INFO ][plugins.apm] Saved latest agent settings to Fleet integration policy for APM.
[2022-01-24T09:32:29.263+00:00][INFO ][plugins.apm] Updating config systemtest_service/undefined
[2022-01-24T09:32:29.548+00:00][INFO ][plugins.apm] Saved latest agent settings to Fleet integration policy for APM.
[2022-01-24T09:34:30.453+00:00][ERROR][plugins.fleet] Unable to create package policy. Package 'apm' already exists on this agent policy.
```

Merging related package update in https://github.com/elastic/package-storage/pull/3330 for testing already.

**Comment by simitt** [comment]
Apologies for the force-push after moving it out of draft - had messed up the base and pushed it already.

**Review by axw — APPROVED** [review]
thank you!

**Pull request merged**
