### PR TITLE
Docs: Asciidoctor compatibility (7.0) (#2567)

### PR DESCRIPTION
**Pull request by nik9000**
Fixes all build errors I found when trying to build the docs using
asciidoctor in the master branch.

### CODE REVIEW

**Comment by bmorelli25** [comment]
Did you test this one? It doesn't build for me

**Comment by nik9000** [comment]
> Did you test this one? It doesn't build for me

I did! let me do it again....

**Comment by nik9000** [comment]
> I did! let me do it again....

It works with *asciidoc* but not *asciidoctor*. It helps asciidoctor, but isn't enough. I figured I'd grab other changes in another PR set.

**Comment by bmorelli25** [comment]
Yes, that's my fault. Accidentally was still testing on asciidoctor. LGTM

**Comment by nik9000** [comment]
> Yes, that's my fault. Accidentally was still testing on asciidoctor. LGTM

I'm trying both when I go, sort of hopeful but not expecting it to work.

**Pull request merged**
