### PR TITLE
test: fix BenchmarkOTLPTraces consistently failing

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

the benchmark function can panic or call runtime.Goexit under the hood (FailNow/SkipNow) stopping the goroutine. That will cause the benhmark executor to report the benchmark as a failure which is a big if the test was skipped.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## Related issues

Closes https://github.com/elastic/apm-server/issues/9844

### CODE REVIEW

**Review by marclop — APPROVED** [review]
Looks good!

**Comment by marclop** [comment]
Looks like the OTLP benchmarks still failed since they're reporting NaN:

```
16:12:54  BenchmarkOTLPTraces-512      	       0	               NaN ns/op	       0 B/op	       0 allocs/op
16:12:55  BenchmarkOTLPTraces-512      	       0	               NaN ns/op	       0 B/op	       0 allocs/op
16:12:57  BenchmarkOTLPTraces-512      	       0	               NaN ns/op	       0 B/op	       0 allocs/op
16:12:57  make[1]: Leaving directory '/var/lib/jenkins/workspace/apm-server_benchmarks_PR-9869/src/github.com/elastic/apm-server/testing/benchmark'
16:12:57  /var/lib/jenkins/workspace/apm-server_benchmarks_PR-9869/.gvm/versions/go1.19.4.linux.amd64/bin/go build -o /var/lib/jenkins/workspace/apm-server_benchmarks_PR-9869/src/github.com/elastic/apm-server/build/linux/gobench -modfile=/var/lib/jenkins/workspace/apm-server_benchmarks_PR-9869/src/github.com/elastic/apm-server/tools/go.mod github.com/elastic/gobench
16:12:57  go: downloading github.com/elastic/gobench v0.0.0-20220608141032-f30bc57e329c
16:12:57  go: downloading github.com/blang/semver v3.5.1+incompatible
16:12:57  go: downloading github.com/kr/pretty v0.3.0
16:12:57  go: downloading golang.org/x/tools v0.1.12
16:12:57  go: downloading github.com/kr/text v0.2.0
16:12:57  go: downloading github.com/rogpeppe/go-internal v1.9.0
16:12:57  go: downloading golang.org/x/sys v0.0.0-20220908164124-27713097b956
16:13:19  2022/12/22 04:13:18 json: unsupported value: NaN
16:13:19  Makefile:99: recipe for target 'index-benchmark-results' failed
16:13:19  make: *** [index-benchmark-results] Error 1
```

**Comment by kruskall** [comment]
> Looks like the OTLP benchmarks are not failing, but upon reporting the numbers as NaN, are triggering a failure on the indexing target:

Good catch! I've pushed some changes.

**Comment by marclop** [comment]
Benchmarks passed 🎉

**Review by marclop — APPROVED** [review]

**Pull request merged**
