### PR TITLE
Fix npm module error

### PR DESCRIPTION
**Pull request by Barathwaja**
NPM Module renamed error

### CODE REVIEW

**Comment by Barathwaja** [comment]
@watson I was doing a pilot run on APM with Node, while installing I got the error.

elastic-apm

**Comment by watson** [comment]
Got'ya 👍 The reason why I ask is because this PR is made against a very old version of the documentation that's only visible for version 6.0 of the APM Server. So I was just curious if you had typed in `elastic-apm` by a mistake or if you are actually using APM Server version 6.0.x and therefore were reading the old documentation?

**Comment by simitt** [comment]
@watson what's the status of this PR?

**Comment by watson** [comment]
@Barathwaja I'll go ahead and close this PR for now to keep things tidy in the repo. If you still want to work on it and get it merged, just let me know and I can re-open it 🙂 I'll be happy to help you land it.

**Pull request closed without merging**
