### PR TITLE
Update beats framework to 3a51720

### PR DESCRIPTION
**Pull request by graphaelli**

### CODE REVIEW

**Comment by graphaelli** [comment]
jenkins, run package tests please

**Comment by graphaelli** [comment]
jenkins, run package tests please

**Comment by simitt** [comment]
@graphaelli I hope you don't mind:
- I updated to the latest beats master to get some changes in I need for https://github.com/elastic/apm-server/pull/1712
- and rebased on apm-server master to make the failing tests pass.

**Comment by graphaelli** [comment]
That's great, thanks!

**Comment by simitt** [comment]
@graphaelli are you working on adding the missing attributes to the Kibana Index Pattern in the Kibana repo (see [failing sync test](https://apm-ci.elastic.co/job/elastic+apm-server+pull-request+multijob-synced/340/console)? Otherwise I can add them.

**Comment by graphaelli** [comment]
thanks @simitt

**Comment by simitt** [comment]
jenkins, retest this please

**Comment by simitt** [comment]
jenkins, run package tests please

**Pull request merged**
