### PR TITLE
bump version to 7.12.2

### PR DESCRIPTION
**Pull request by simitt**

### CODE REVIEW

**Review by graphaelli — APPROVED** [review]

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
The `"[localhost:49155 localhost:49155]" should have 1 item(s), but has 2` system test failure is fixed on master but not yet backported. It's just a test issue, and there are conflicts backporting - so I'll probably merge this and fix the backport later. Just waiting for everything else to go green first.

**Pull request merged**
