### PR TITLE
Update apm-data: set a default `span.representative_count`

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Update to apm-data changes:
 - https://github.com/elastic/apm-data/pull/30 (`span.representative_count` now defaults to 1)
 - https://github.com/elastic/apm-data/pull/33 (removes `modelprocessor.DroppedSpansStatsDiscarder`, now filtered in encoding)
 - https://github.com/elastic/apm-data/pull/35 (overhauled JSON encoding approach)

The metrics data structure has changed, so a new common ingest pipeline is added to handle these. We now send metrics as 

```json
"metricset.samples": [
  {"name": "metric_name1", "type": "histogram", "unit": "s", "values": [1, 2, 3], "counts": [4, 5, 6]},
  {"name": "metric_name2", "type": "summary", "value_count": 123, "sum": 456},
  {"name": "metric_name3", "type": "counter", "value": 123}
  {"name": "metric_name4", "value": 456}
]
```

The ingest pipeline takes care of mapping these to top-level metric fields as before.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

The only functional change should be the `span.representative_count` one. This can be tested by sending spans, with destination fields set, to the server without `sample_rate` set, and checking that (a) the span documents indexed have `representative_count: 1`, and (b) service_destination metrics are produced.

## Related issues

Closes https://github.com/elastic/apm-server/issues/3565

### CODE REVIEW

**Comment by simitt** [comment]
I suggest to split the change for the metricset and the `span.representative_count` into two separate PRs as they are unrelated.

**Comment by axw** [comment]
I've pulled the apmpackage changes into https://github.com/elastic/apm-server/pull/10793

**Comment by axw** [comment]
Waiting for https://github.com/elastic/kibana/pull/157450 to be merged.

**Review by marclop — APPROVED** [review]

**Comment by axw** [comment]
Testing this myself since I didn't actually make the representative_count change.

**Comment by axw** [comment]
Tested in conjunction with https://github.com/elastic/apm-server/pull/10922. Verified with 8.9.0-BC1.

**Pull request merged**
