### PR TITLE
ci(jenkins): update timeout and when regexp comparator

### PR DESCRIPTION
**Pull request by v1v**
## Highlights
- As there are more parallel stages/branches, let's reduce the timeout
- Update when using the regexp comparator.

Depends on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/351

### CODE REVIEW

**Comment by v1v** [comment]
Apparently, the comparator only works for the tags rather than branches, I'll raise a PR to the upstream to support this particular specs. So I'll keep this particular PR open until the upstream plugin supports it.

**Comment by simitt** [comment]
@v1v any updates on that? Could you link the upstream PR here?

**Comment by v1v** [comment]
It's now supported in the upstream:
- https://github.com/jenkinsci/pipeline-model-definition-plugin/releases/tag/pipeline-model-definition-1.4.0

We might need to wait for the upcoming upgrade of our current CI environment to be able to use this feature.

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by v1v** [comment]
We are good to go, current build issues are not relevant to this particular PR though

**Pull request merged**
