### PR TITLE
Bump up version to prepare for 8.10.3

### PR DESCRIPTION
**Pull request by lahsivjar**

### CODE REVIEW

**Review by marclop — COMMENTED** [review]
you need to also update the apmpackage changelog to contain `8.10.3`.

**Comment by lahsivjar** [comment]
> you need to also update the apmpackage changelog to contain 8.10.3.

@marclop There are no changes to the apmpackage I think. I was under the impression that in such cases we don't make any changes.

**Comment by marclop** [comment]
I agree with you, but the `make check-full` target will fail and tell you due to the version bump.

**Comment by marclop** [comment]
oh never mind... Seems I was mistaken, ignore my comment

**Review by dmathieu — APPROVED** [review]

**Pull request merged**
