### PR TITLE
disable metrics logging by default

### PR DESCRIPTION
**Pull request by jalvz**
Any reason not to do this?

### CODE REVIEW

**Comment by roncohen** [comment]
I've seen that the beats team often make use of the metrics to help debug issues. It's a lot simpler to do if those are on by default.

**Comment by jalvz** [comment]
Because for me it dominates & pollutes the logs to the point where it actually hurts readability. I never used them to debug any issues, not even when we had big performance/scalability problems.
(Another story might be the metrics pushed to ES that can be queried in dashboards, etc. but this is just about the logs)

Also: we are going to release application metrics because monitoring does not fit exactly the required use case, right? 
We don't log the actual application metrics  (just push them to ES); so why monitoring shouldn't be the same?

However, if any of you have insights/experience with effectively troubleshooting apm-server issues with monitoring logs, I would like to learn how you did it!

**Comment by simitt** [comment]
I don't have any strong opinion on that tbh, so I am fine either way.

**Comment by graphaelli** [comment]
I also don't have a strong opinion on doing this for users.  FWIW, I always have this when running locally.

**Comment by jalvz** [comment]
Cool. So is this _approved_ or _rejected_ ?

**Comment by roncohen** [comment]
I don't feel strongly either way 👍

**Pull request merged**
