### PR TITLE
Fix indentation in instrumentation section of config

### PR DESCRIPTION
**Pull request by Guerteltier**
## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

I have considered changes for:
- [ ] documentation
- [ ] logging (add log lines, choose appropriate log selector, etc.)
- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))
- [ ] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
- [ ] telemetry
- [ ] Elasticsearch Service (https://cloud.elastic.co)
- [ ] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)
- [ ] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)

### CODE REVIEW

**Review by axw — COMMENTED** [review]
Thanks for the fix! This should be made in `_meta/beat.yml`. After updating that file, please run `make config` to regenerate `apm-server.yml`.

**Comment by Guerteltier** [comment]
Done. :)

**Review by axw — APPROVED** [review]

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
Thanks again @Guerteltier !

**Pull request merged**
