### PR TITLE
Use service.version for Metadata.Service.Version when converting a Jaeger span

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
Unrelated test failure, opened #4062

**Comment by simitt** [comment]
open to test - needed backport for `7.10`

**Comment by simitt** [comment]
tested with BC2 - works with span specific tags; 
for process specific tags there's a follow up issue open https://github.com/elastic/apm-server/issues/4319.

**Pull request merged**
