### PR TITLE
test: cleanup systemtest init

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

we don't need to upload apmpackage so we can cleanup the init code. Avoid cleaning es during init, it should be cleaned in specific tests to support the -count flag.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by v1v** [comment]
run docs-build

**Review by carsonip — COMMENTED** [review]
> Avoid cleaning es during init, it should be cleaned in specific tests to support the -count flag.

which -count flag are you referring to?

**Comment by axw** [comment]
> @axw do we still need to install the APM package for systemtests ? Do you think this makes sense now that we have the apm data plugin ?

I don't think we need it any more. The tests pass... :)
We're still using Fleet in ESS, and we have smoke tests there, so I think we're covered.

> Avoid cleaning es during init, it should be cleaned in specific tests to support the -count flag.

I don't follow this. If the individual tests still clean up ES, how will `-count` work?

**Comment by axw** [comment]
> Individual tests cleaning up ES is the correct behaviour. If we rely on TestMain then it will be cleaned once when the first test run and every other iteration specified in -count won't clean ES.

Gotcha. Makes sense.

**Review by axw — APPROVED** [review]

**Pull request merged**
