### PR TITLE
fix: accept --environment macos_service and udpate testcase to avoid race condition

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

The env variable is a loop variable and is captured by the func which is executed in parallel.
As a result the test only runs with `windows_service` and the other values are never tested.
Ironically one of the untested values is currently broken: https://github.com/elastic/elastic-agent-libs/pull/101

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by kruskall** [comment]
PR on elastic-agent-libs has been merged. I've released a new version and bumped the library here.

Do we want to backport this ?

**Review by carsonip — APPROVED** [review]
good catch! is the go mod bump needed?

**Comment by kruskall** [comment]
> good catch! is the go mod bump needed?

Yes, the bug is in the library: https://github.com/elastic/elastic-agent-libs/pull/101

**Comment by axw** [comment]
Oof! Good catch, thank you!

**Pull request merged**
