### PR TITLE
[Fleet] Fix the agent template to support multi variables

### PR DESCRIPTION
**Pull request by nchaulet**
## Description 

Resolve https://github.com/elastic/kibana/issues/102022

In Fleet multi variables need to manually be handled in handlebars template. 
That PR fix it for the multi variables used by APM 

## Generated policy 

```
inputs:
  - id: bd901103-c626-43b7-8362-a9157bc99d81
    name: apm-1
    revision: 1
    type: apm
    use_output: default
    meta:
      package:
        name: apm
        version: 0.3.0
    data_stream:
      namespace: default
    apm-server:
      host: 'localhost:8200'
      secret_token: null
      max_event_size: 307200
      capture_personal_data: true
      default_service_environment: null
      rum:
        enabled: false
        source_mapping.elasticsearch.api_key: null
        allow_service_names:
          - name1
          - name2
        allow_origins:
          - '*'
        allow_headers:
          - header1
          - header2
        library_pattern: null
        exclude_from_grouping: null
        response_headers: null
        event_rate.limit: 300
        event_rate.lru_size: 1000
      api_key:
        enabled: false
        limit: 100
      agent_config: []
      ```

### CODE REVIEW

**Review by simitt — APPROVED** [review]
Thanks @nchaulet, I wasn't aware of that!

**Comment by nchaulet** [comment]
@simitt not sure why the CI is failing here

**Comment by simitt** [comment]
@nchaulet looks completely unrelated - could you try update to the latest `master`?

**Comment by axw** [comment]
Thanks @nchaulet !

**Comment by axw** [comment]
Verified with 7.14 BC1

image

**Pull request merged**
