### PR TITLE
Test SNAPSHOT in smoketests

### LINKED ISSUE #13051: Fix/Improve APM Server Smoke Tests
We have been repeatedly running into issues with smoketests and they need some re-work. 

This task is to 

(1) check whether there is some smoke test failure fatigue. Are there common scenarios where smoke tests fail and it is _expected_, e.g. after a version bump? 
If that is the case, can we make it easier to quickly distinguish such failures from other failures? E.g. does it make sense to split some of the smoke tests up, and have separate triggers and slack notifications for them? Can the failure message and which exact test failed be brought back to slack? Other ideas? 

(2) The tests for `latest` are shown as success, but really they are skipped:

Screenshot 2024-04-25 at 08 04 29

I assume the `latest` is supposed to test the latest `7.x` and `8.x` versions that are not yet released. We need to have smoke tests running for unreleased versions.

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

Support "latest" in lagacy-managed and legacy-standalone-major-managed by testing snapshots.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

```shell
(cd testing/smoke/legacy-standalone-major-managed && EC_API_KEY=redacted ./test.sh latest)
(cd testing/smoke/legacy-managed && EC_API_KEY=redacted ./test.sh latest)
```

## Related issues

Part of #13051

### CODE REVIEW

**Comment by carsonip** [comment]
This should be tested again when 7.17 snapshot is fixed. Currently 7.17.22-SNAPSHOT is broken and APM doesn't start.

**Comment by simitt** [comment]
>Currently 7.17.22-SNAPSHOT is broken and APM doesn't start.

Could you link to a tracking issue for this please?

**Comment by carsonip** [comment]
> > Currently 7.17.22-SNAPSHOT is broken and APM doesn't start.
> 
> Could you link to a tracking issue for this please?

The issue should be https://github.com/elastic/beats/pull/39585

**Comment by carsonip** [comment]
I can confirm that the 7.17 build is fixed and both updated smoke tests now pass.

**Review by inge4pres — APPROVED** [review]
👍🏼 thanks

**Review by kyungeunni — APPROVED** [review]

**Pull request merged**
