### PR TITLE
Universal Profiling: Remove all UP-related code and tests

### PR DESCRIPTION
**Pull request by christos68k**
### Summary

UP now runs outside of APM server starting from 8.9.

**NOTE:** This should NOT be merged unless the profiling team has signed off on merging, specifically. In the meantime it's useful to have reviews done so that this PR becomes mergeable.

There are standalone profiling tests remaining to be performed in production and we'd like to keep UP-in-APM-server available as a backup in case we run into major problems. The expectation being that no major issues arise and we merge this as part of 8.9.

### CODE REVIEW

**Review by kruskall — APPROVED** [review]

**Review by axw — APPROVED** [review]

**Review by rockdaboot — APPROVED** [review]
LGTM

**Review by florianl — APPROVED** [review]

**Comment by simitt** [comment]
The PR is in conflict, please let us know once this should be merged.

**Comment by christos68k** [comment]
> The PR is in conflict, please let us know once this should be merged.

I'll do the rebase and (hopefully!) merge tomorrow.

**Comment by christos68k** [comment]
@simitt @axw We've now checked off on this so feel free to do a final review pass and merge (I fixed the conflicts).

**Pull request merged**
