### PR TITLE
feat: grab docker container logs after run tests

### LINKED ISSUE #2941: Grab docker-compose logs
in some cases, we do not have a clear error in the test and we need the Docker container logs to diagnose the problem, so we are going to implement the same solution we have in the integration test that grabs the Docker container logs at the end of the test.

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

This PR adds a script to grab the Docker container logs at the end of the tests.

## Why is it important?

Sometimes those logs give additional information about the failures.

## Related issues
Closes #2941

### CODE REVIEW

**Comment by simitt** [comment]
Why are the system tests read although details show OK?

**Comment by kuisathaverat** [comment]
>Why are the system tests read although details show OK?

Do you mean, Why we grab the logs even do the test are successful? to avoid having to check if the test pass or not, grab the logs worth in any case and takes a few seconds at the end of the system test.

**Comment by simitt** [comment]
Sorry I actually had a typo, I meant why the system tests were `red` not `read`. Grabbing the logs always SGTM.

**Comment by kuisathaverat** [comment]
@simitt I've forgotten setting the script permissions, it is resolved now.

**Comment by kuisathaverat** [comment]
@simitt I've added a step to grab the junit results from the System test, there are some test failing but I don't think are related to my PR 

These are the test
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-2948/6/tests

An now we have also the Docker container logs and info
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-2948/6/artifacts

in docker-info/docker-containers.txt you have the list of containers with the ID to identify the files.

**Pull request merged**
