### PR TITLE
[7.x] Add fingerprint calculation for servicemaps to spans. (#3374)

### PR DESCRIPTION
**Pull request by simitt**
Backports the following commits to 7.x:
 - Add fingerprint calculation for servicemaps to spans. (#3374)

### CODE REVIEW

**Comment by simitt** [comment]
jenkins run the tests please

**Comment by simitt** [comment]
Closing for now, until https://github.com/elastic/apm-server/issues/3421 is clarified.

**Comment by axw** [comment]
Added to test plan to ensure nothing slipped into 7.7.0

**Comment by jalvz** [comment]
So the test here is ensuring that the fingerprint field is not there?

**Comment by axw** [comment]
@jalvz correct

**Pull request closed without merging**
