### PR TITLE
[7.x] Clarify error message when unauthorized Kibana connection (#3753)

### PR DESCRIPTION
**Pull request by jalvz**
Backports the following commits to 7.x:
 - Clarify error message when unauthorized Kibana connection (#3753)

### CODE REVIEW

**Comment by axw** [comment]
Will need to wait for a new BC to test this one.

**Comment by axw** [comment]
If I don't have any kind of auth enabled in apm-server, then with invalid/missing kibana auth I get this response when querying agent config:

```
$ curl http://localhost:8200/config/v1/agents?service.name=foo

{                                       
  "error": "Unauthorized"         
}
```

I'm not sure that behaviour is quite right, but it's existing behaviour. What I'm not sure about is whether we should be suppressing the error message when the server doesn't have any auth enabled. It certainly makes sense to suppress it when it's enabled but not supplied.

If I enable secret token auth in apm-server, and send a secret token in the query, I see the full message:

```
$ curl -H "Authorization: Bearer hunter2" http://localhost:8200/config/v1/agents?service.name=foo

{
  "error": "APM Server is not authorized to query Kibana. Please configure apm-server.kibana.username and apm-server.kibana.password, and ensure the user has the necessary privileges."
}
```

**Comment by axw** [comment]
@jalvz is that behaviour expected?

**Comment by jalvz** [comment]
Yes, I followed the same logic from other cases:
https://github.com/elastic/apm-server/blob/6270692644f0cb75e75ee0617fc96b3d7ce2146a/beater/api/config/agent/handler.go#L177 (`authErrMsg`)

**Pull request merged**
