### PR TITLE
Add global labels to service_destination metrics

### LINKED ISSUE #10045: Add global labels to service_destination metrics
We want to allow using global labels for filtering APM data everywhere in the APM UI. For this to work, global labels also need to be added to the `service_destination` (span) metrics. 

The groundwork for adding labels is already done via https://github.com/elastic/apm-server/tree/main/x-pack/apm-server/aggregation/labels.

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

Add global labels to service_destination metrics for filtering APM data in APM UI

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
~~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~~
~~- [ ] Documentation has been updated~~

## How to test these changes

- Confirm that global labels are present in service_destination metrics

## Related issues

Closes #10045

### CODE REVIEW

**Review by simitt — APPROVED** [review]
LGTM

**Comment by marclop** [comment]
I tested with 8.7.0 BC2 on ESS but seems like we have a regression since the data streams don't have mappings for the `labels` object (I suspect `numeric_labels` either):

```
failed to index document (strict_dynamic_mapping_exception): mapping set to strict, dynamic introduction of [labels] within [_doc] is not allowed
```

Using this Go program and script below:

```go
package main

import (
	"fmt"
	"time"

	"go.elastic.co/apm/v2"
)

func main() {
	tracer := apm.DefaultTracer()
	tracer.SetSpanCompressionEnabled(false)             // Disable compression.
	tracer.SetExitSpanMinDuration(2 * time.Millisecond) // set duration to 2ms.
	tx := tracer.StartTransaction(fmt.Sprintf("tx"), fmt.Sprintf("type"))
	duration := 100
	for i := 0; i < 20_000; i++ {
		span := tx.StartSpanOptions(fmt.Sprintf("span-%d", i), fmt.Sprintf("type-%d", i), apm.SpanOptions{
			ExitSpan: true,
		})
		span.Context.SetServiceTarget(apm.ServiceTargetSpanContext{
			Name: fmt.Sprintf("dest-%d", i),
			Type: fmt.Sprintf("res-%d", i),
		})
		span.Duration = time.Duration(duration) * time.Millisecond
		span.End()
		if i%500 == 0 {
			tracer.Flush(nil)
		}
	}
	tx.Duration = time.Duration(duration) * time.Millisecond
	tx.End()
	tracer.Flush(nil)
	fmt.Printf("%+v\n", tracer.Stats())
}
```

```bash
#!/bin/bash

export ELASTIC_APM_SERVER_URL=${1:-"http://localhost:8200"}
export ELASTIC_APM_GLOBAL_LABELS=department_name=apm,organization=observability,company=elastic
export ELASTIC_APM_SERVICE_NAME=apm
go run main.go

export ELASTIC_APM_GLOBAL_LABELS=department_name=fleet-server,organization=observability,company=elastic
export ELASTIC_APM_SERVICE_NAME=fleet-server
go run main.go

export ELASTIC_APM_GLOBAL_LABELS=department_name=kibana,organization=platform,company=elastic
export ELASTIC_APM_SERVICE_NAME=kibana
go run main.go
```

**Comment by carsonip** [comment]
Fixing in #10297

**Comment by marclop** [comment]
Verified with BC5 on ESS

**Pull request merged**
