### PR TITLE
Use deployment.environment for Metadata.Service.Environment when converting a Jaeger span.

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Motivation/summary

deployment.environment is used in OpenTelemetry and already converted to Metadata.Service.Environment for OpenTelemetry spans. It would be nice if it is also supported for Jaeger spans.

## Checklist
- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] ~Documentation has been updated~

### CODE REVIEW

**Review by axw — COMMENTED** [review]
Thanks for the PR @tobiasstadler.

I'm not sure if this is needed. Jaeger has "tracer tags" (aka "process tags"), which will be translated to "resource" in OTel.

Can you set `deployment.environment` as a tracer tag rather than span tag? You should be able to do this with an environment variable (`JAEGER_TAGS=deployment.environment=production`) or in code.

**Comment by tobiasstadler** [comment]
Setting process tags works. Thank You!

**Comment by axw** [comment]
Thanks for confirming.

@tobiasstadler you may recall adding support for `service.version` back in https://github.com/elastic/apm-server/pull/4061. That should probably also be set in tracer tags. How would you feel about us deprecating setting service version in span tags?

**Comment by tobiasstadler** [comment]
I am fine with deprecating it.

**Pull request closed without merging**
