### PR TITLE
ci: fix ONLY_DOCS condition

### LINKED ISSUE #9704: Skip CI on docs-only PRs
### Summary

There are a lot of CI checks that run on APM Server PRs. Can we skip most checks when a docs-only PR is opened? Either a PR that only touches `*.asciidoc` files, or only touches files in the `docs/` dir. This would save $$ and allow me to merge PRs faster 😄.

FWIW, the Kibana repo has been doing this for a while, and it works well. Kibana docs-only PRs only run the CLA check, `elasticsearch-ci/docs Build`, and a couple of labeling checks. Here's an [example](https://github.com/elastic/kibana/pull/144374).

### PR DESCRIPTION
**Pull request by reakaleek**
## Motivation/summary

Skipping certain stages if only asciidoc files were changed did not work as expected. The reason is that environment variables defined in the `environment {}` block cannot be overridden. Therefore, `env.ONLY_DOCS` always stayed `"false"`.

Also see: https://github.com/elastic/apm-server/issues/9704#issuecomment-1352450206

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

1. Create a new PR based on this branch which only has changes to asciidoc files.
1. Check if pipeline is executing the following stages (it should not)
   - Unit tests - linux/amd64 
   - Unit tests - linux/arm64
 

## Related issues

Closes #9704

### CODE REVIEW

**Review by bmorelli25 — COMMENTED** [review]
Welcome to Elastic! Nice to meet you. Thanks for taking on this problem 😄

**Comment by cachedout** [comment]
Thanks for this @reakaleek. I'd like @kuisathaverat to review this before merging but it seems ok to me.

**Comment by reakaleek** [comment]
> Welcome to Elastic! Nice to meet you. Thanks for taking on this problem 😄

@bmorelli25 thank you! Nice to meet you too.

> I'm not sure how to test this, so I'll just leave a comment for now...

Yup, quite inconvenient to test. After this PR is merged and you happen to create a new docs PR, let me know if the behaviour is as expected.  

I verified this by temporarily changing the pattern to `(.*\.asciidoc|\.ci\/Jenkinsfile)` and adding a random change to any asciidoc file.

**Comment by reakaleek** [comment]
How can I re-trigger the CLA status check?

**Review by kuisathaverat — APPROVED** [review]

**Comment by reakaleek** [comment]
@kuisathaverat 

Looking at https://github.com/elastic/apm-server/pull/4395 I noticed that those changes were backported.

Do we need to do the same for this case?

**Comment by kuisathaverat** [comment]
>Do we need to do the same for this case?

yes, it make sense

**Pull request merged**
