### PR TITLE
update-beats

### PR DESCRIPTION
**Pull request by stuartnelson3**
beats recently updated to the new go1.16.6

### CODE REVIEW

**Review by axw — CHANGES_REQUESTED** [review]
There are a handful of other files that should be updated when upgrading the Go version, can you please update them too?
 - README.md
 - CHANGELOG.asciidoc
 - docs/version.asciidoc
 - tests/Dockerfile
 - Dockerfile

**Comment by stuartnelson3** [comment]
Where should I update the changelog in a version branch? I've only updated `changelogs/head.asciidoc`, which isn't present, and there's no 7.14 changelog yet.

**Comment by axw** [comment]
Sorry, I missed that this is against 7.14. Ignore comment about changelog then.

**Comment by stuartnelson3** [comment]
@axw any idea if these are legitimate failures? Last two runs failed on a rum integration test, which I don't think I've seen fail before.

https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5744/3/testReport/tests.agent/test_rum/Build_and_Test___APM_Integration_Tests___test_rum/

**Comment by axw** [comment]
These failures are unrelated, merging

**Pull request merged**
