### PR TITLE
Switch to standard ESS trial links

### PR DESCRIPTION
**Pull request by nrichers**
## Motivation/summary

This PR switches trial sign-up links over to the standard attribute we're introducing that should provide some metrics for how effective these links are.﻿

Details for the attribute are in https://github.com/elastic/docs/pull/1737, if you want to know more. 

@bmorelli25 if you could review this PR, I would be grateful. I'd also appreciate any pointers you have for getting these changes into all the right branches.  

## Checklist

- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)
- [ ] I have rebased my changes on top of the latest master branch

- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes

- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by bmorelli25** [comment]
Actually, it looks like query params work on the product page as well: `https://www.elastic.co/elasticsearch/service?baymax=docs-body&elektra=docs` Can we add another attribute to track links to that page as well?

**Comment by bmorelli25** [comment]
One more question: How far have you been backporting this in other product repos? I'm happy to handle the merge/backport process for this repo.

**Comment by nrichers** [comment]
@bmorelli25 excellent questions!

> Should non-signup links should be adjusted to point to sign up pages instead? 

Our docs vision says that "[e]very link and referral to Elastic Cloud from Elastic documentation should be tracked and results made available in regular reports." Since this isn't specific to trials, we might well want to track these other links just so we have some data available. I'd suggest we'd handle these additional link changes with a different PR, though, since there are still some details to be sorted out. 

I did do a bit of investigation into non-signup links before and searched all the repos we build docs out of. Put what I found [on the agenda for our next workgroup meeting](https://docs.google.com/document/d/1wKgmy8xD2cQauS9iXt0zaGSxIdrJ4PLFunP4ATWsx4o/edit#bookmark=id.o6rtbsgusiof) to discuss. 

> Actually, it looks like query params work on the product page as well: https://www.elastic.co/elasticsearch/service?baymax=docs-body&elektra=docs Can we add another attribute to track links to that page as well?

Since we care about the financial impact of trial sign-ups from the docs, we might want to use a different tracking parameter for non-signup links. We can use anything we like, `?baymax=docs-body` is just something we came up with. 

> One more question: How far have you been backporting this in other product repos? I'm happy to handle the merge/backport process for this repo.

If you don't mind handling the backporting, that would be awesome! I _finally_ learned how to use the backport tool (Cloud uses an auto-merge tool that's quite different), but it seems every product does things slightly differently. Typically, the PRs for switching to the `{ess-trial}` attribute have gone into `master`, `7.x`, `7.6`, and sometimes `6.8`.

**Comment by bmorelli25** [comment]
Thanks for the thorough response!

> Our docs vision says that "[e]very link and referral to Elastic Cloud from Elastic documentation should be tracked and results made available in regular reports." Since this isn't specific to trials, we might well want to track these other links just so we have some data available.

I would actually argue that the [product page link](https://www.elastic.co/cloud/elasticsearch-service) _is_ specific to trials, as its hero banner with integrated sign-up form is almost identical to the [signup link](https://www.elastic.co/cloud/elasticsearch-service/signup?baymax=docs-body&elektra=docs). But I'm happy to move forward with this and reassess later if that's the plan 😄 

> Typically, the PRs for switching to the {ess-trial} attribute have gone into master, 7.x, 7.6, and sometimes 6.8.

Sounds good!

**Pull request merged**
