### PR TITLE
Update beats framework to 912ef57

### PR DESCRIPTION
**Pull request by simitt**

### CODE REVIEW

**Comment by simitt** [comment]
jenkins, run package tests please

**Comment by jalvz** [comment]
if you open a Pr in kibana with title like "[APM] Update index pattern" and re-trigger tests here, we can see if the plumbing i did works and get that sync test passing.

**Comment by simitt** [comment]
There is no PR in Kibana, the index pattern is up to date. The sync test failed, because with this update the Kibana Index Pattern does not get created by running `make update` anymore, but one needs to specifically call `./apm-server export index-pattern` now. [This commit](https://github.com/elastic/apm-server/pull/1881/commits/1684493f141fdb677ad816fdecf5df4ba59d9c9c) fix it.

**Comment by jalvz** [comment]
ah, great. thanks

**Comment by simitt** [comment]
cc @ruflin the Kibana index pattern changes seem to work smoothly.

**Pull request merged**
