### PR TITLE
test: replace env workaround with native T.SetEnv

### PR DESCRIPTION
**Pull request by kruskall**
## Motivation/summary

Go 1.17 added native test tmp directories, adding support
for  setting an environment variable for the duration of
the test or benchmark.  

See https://pkg.go.dev/testing#T.Setenv  
See https://tip.golang.org/doc/go1.17#testing

## Checklist

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

`make test`

## Related issues

None

### CODE REVIEW

**Review by axw — APPROVED** [review]
Thanks again!

**Comment by axw** [comment]
CI is failing because `systemtest/environment_test.go` needs formatting -- looks like the `os` import might not be used anymore. Can you please run `make gofmt`?

**Comment by kruskall** [comment]
> CI is failing because `systemtest/environment_test.go` needs formatting -- looks like the `os` import might not be used anymore. Can you please run `make gofmt`?

Sorry about that :facepalm:  

Thank you for help! I've pushed some changes :ping_pong:

**Comment by axw** [comment]
@kruskall no worries. We will squash commits when merging.

Can you please take a look at the test failures? https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-8239/3/testReport/

**Pull request merged**
