### PR TITLE
Added support for transaction.name in an error object to the intake API

### LINKED ISSUE #6529: Allow `transaction.name` in error events
See https://github.com/elastic/apm/issues/531

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Motivation/summary
Fixes #6529

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes
I added unit tests

### CODE REVIEW

**Comment by tobiasstadler** [comment]
I ran `make update` this time

**Review by axw — APPROVED** [review]
Whoa, you're quick :) Thank you!

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by stuartnelson3** [comment]
test plan: ingest an error, verify transaction.name is set

**Comment by marclop** [comment]
Tested locally ingesting some errors with `8.0.0-dev4` package but we missed adding the `transaction.name` field mapping to the data stream:

### Error detail
image

### Data Stream mapping

image

**Comment by marclop** [comment]
Verified this with 42889b423, which contains the linked PR's fix.

**Pull request merged**
