### PR TITLE
Move breaking change to its section

### PR DESCRIPTION
**Pull request by jalvz**
@bmorelli25 how can we highlight that is change belongs to an experimental feature?

### CODE REVIEW

**Comment by bmorelli25** [comment]
@simitt did you make a decision on how you want to handle breaking changes for beta features? Let me know and I can update this PR accordingly.

**Comment by simitt** [comment]
Yes @bmorelli25 we go with the suggested approach of having them in the breaking changes section but clearly label as `beta` or `experimental`. It would be great if you could take over this PR.

**Comment by bmorelli25** [comment]
jenkins, test this please

**Comment by bmorelli25** [comment]
Here's what I came up with. The bubble expands on hover.

Screen Shot 2021-07-12 at 2 53 24 PM

**Review by axw — APPROVED** [review]
this looks very clear, thanks @bmorelli25 !

**Pull request merged**
