### PR TITLE
docs: Add "Known issues" page

### LINKED ISSUE #11282: Create Known Issues section in release notes
Create a dedicated section _Known Issues_ in apm-server docs. The goal is that all known issues from a specific version are easily searchable and users can get a good overview before upgrading to a certain version. 

The discussed approach is as follows:
* have one common asciidoc where known issues are collected
* per release note version, pull in the existing known issues from the common file

### PR DESCRIPTION
**Pull request by colleenmcginnis**
Closes #11282

Creates a new "Known issues" page with suggested formatting for listing known issues. There are not currently any known issues listed. I found two existing known issues ([`8.5.asciidoc`](https://github.com/elastic/apm-server/blob/main/changelogs/8.5.asciidoc#known-issue) and [`7.9.asciidoc`](https://github.com/elastic/apm-server/blob/main/changelogs/7.9.asciidoc)), but I'm not sure if they still apply to more recent versions. From @simitt:

>we'll need to go through a couple of different sources to pull the Known Issues together.

@simitt I'll let you tag others to help identify existing known issues, and then I can help with any necessary copy editing, reformatting once we know what the content will look like, and cross-referencing between release notes and this new page.

### CODE REVIEW

**Comment by simitt** [comment]
@elastic/apm-server please help collecting the _Known Issues_ for `8.10` and `main`

**Comment by simitt** [comment]
@carsonip let's start with collecting the Known Issues for `8.11`. It's probably best to go through open bugs and reported issues and collect the more impactful issues in these docs.

**Comment by colleenmcginnis** [comment]
👋  @simitt @carsonip have you collected any known issues for 8.11 yet?

**Comment by carsonip** [comment]
Sorry I missed the github notification. Yes, we just got a new known issue for 8.11: #12103

**Comment by colleenmcginnis** [comment]
>Sorry I missed the github notification. Yes, we just got a new known issue for 8.11: https://github.com/elastic/apm-server/issues/12103

Thanks @carsonip! Can you take a look at the language and format I used? Here's the preview: [Known issues](https://apm-server_11608.docs-preview.app.elstc.co/guide/en/apm/guide/master/known-issues.html).

**Review by simitt — APPROVED** [review]
Looks good, thanks!

**Comment by carsonip** [comment]
This seems to be missing `backport-8.11`, now adding it back.

**Comment by carsonip** [comment]
@Mergifyio backport 8.11

**Pull request merged**
