### PR TITLE
Rectified all the solution hyperlinks of HTTP 503: Queue is full in L…

### PR DESCRIPTION
**Pull request by TapomoyBhowmik**
The below hyperlinks are wrongly pointed:

In Legacy APM Server Reference documentation - https://www.elastic.co/guide/en/apm/server/current/common-problems.html#queue-full, the solutions have wrong hyperlinks. 

However, APM Guide - https://www.elastic.co/guide/en/apm/guide/7.17/common-problems.html#queue-full has the correct hyperlinks.

Hence, I have updated the below hyperlinks for Legacy APM Server Reference documentation - https://www.elastic.co/guide/en/apm/server/current/common-problems.html#queue-full

Correct Hyperlinks:

Reduce storage - https://www.elastic.co/guide/en/apm/guide/7.17/reduce-storage.html

Tune APM Server output parameters for your Elasticsearch cluster - https://www.elastic.co/guide/en/apm/guide/7.17/tune-apm-server.html#tune-output-config

Adjust internal queue size - https://www.elastic.co/guide/en/apm/guide/7.17/tune-apm-server.html#adjust-queue-size

Tune Elasticsearch for higher ingestion - https://www.elastic.co/guide/en/apm/guide/7.17/tune-es.html

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by TapomoyBhowmik** [comment]
@elastic/docs Could someone please review this pull request? 
Thank you in advance.

**Comment by carsonip** [comment]
Is it intended to merge this into 7.15 branch?

**Comment by simitt** [comment]
@TapomoyBhowmik you created the PR against the `7.15` branch. Can you please point it towards the latest `7.x` branch (`7.17`)?

**Comment by TapomoyBhowmik** [comment]
@simitt Could you please guide me on how to move it to proper version or to latest 7.x branch (7.17)? Do I need to create a new PR for it or I can route it somehow?

Thank you in advance.

**Comment by simitt** [comment]
@TapomoyBhowmik you are touching outdated files here; the latest available documentation pages for `7.x` and `8.x` are up to date:
- `7.17 standalone`: https://www.elastic.co/guide/en/apm/guide/7.17/common-problems.html#queue-full
- `7.17 integration`: there are configuration options available when running the Elastic Agent managed APM integration, so there is no queue-is-full section https://www.elastic.co/guide/en/apm/guide/7.17/troubleshoot-apm.html
- `8.x standalone`: the internal queue and queue is full errors have fully been removed https://www.elastic.co/guide/en/apm/guide/8.6/common-problems-legacy.html
- `8.x integration`: same, the internal queue and queue is full errors have fully been removed https://www.elastic.co/guide/en/apm/guide/8.6/common-problems.html

The original [link](https://www.elastic.co/guide/en/apm/server/current/common-problems.html#queue-full) that you shared is pointing to `7.15`; we are not updating that anymore. 

I'm closing this PR as documentation is as expected; let us know if anything else is unclear.

**Pull request closed without merging**
