### PR TITLE
sampling: use Marshal/UnmarshalVT

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Minor improvement to use generated marshal/unmarshal methods for tail-based sampling. Remove the JSON codec, it's not used anymore.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

N/A, non-functional change.

## Related issues

None

### CODE REVIEW

**Review by lahsivjar — APPROVED** [review]

**Review by marclop — APPROVED** [review]
Looking forward to this! Should a change log entry be added as well?

**Comment by axw** [comment]
> Should a change log entry be added as well?

@marclop I don't think so: there's no functional change, so users shouldn't care.

**Comment by marclop** [comment]
I was thinking that's an improvement where APM Server will be able to store more traces in badger vs before, but perhaps that's not important to point out.

**Comment by axw** [comment]
Ah I see. This was just a switch from reflection-based protobuf encoding/decoding to vtprotobuf-generated code. Maybe we want to talk about the overall switch to using protobuf encoding.

**Pull request merged**
