### PR TITLE
clean up vendor.json

### PR DESCRIPTION
**Pull request by graphaelli**
* add origins
* remove unused packages

### CODE REVIEW

**Comment by simitt** [comment]
Just came accross https://github.com/elastic/apm-server/pull/3271/files#diff-bd290170e2912d3e8694db1a151066e5R262 - could you also ensure the `origin` is added to this newly vendored repo.

**Comment by robgil** [comment]
# [Codecov](https://codecov.io/gh/elastic/apm-server/pull/3272?src=pr&el=h1) Report
> Merging [#3272](https://codecov.io/gh/elastic/apm-server/pull/3272?src=pr&el=desc) into [master](https://codecov.io/gh/elastic/apm-server/commit/3cefdf547e0ca58f923e55541f72965cad487099&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.



```diff
@@           Coverage Diff           @@
##           master    #3272   +/-   ##
=======================================
  Coverage   79.33%   79.33%           
=======================================
  Files         107      107           
  Lines        5600     5600           
=======================================
  Hits         4443     4443           
  Misses       1157     1157           
```

**Comment by graphaelli** [comment]
> How did you add the `origins` wherever they were missing? Can this be added to our update-beats script?

I used https://gist.github.com/graphaelli/714f4965ecf9530c45c77b69334030b5.  It's very hacky and I hope the move to go modules will make it obsolete.

**Comment by graphaelli** [comment]
> Just came accross https://github.com/elastic/apm-server/pull/3271/files#diff-bd290170e2912d3e8694db1a151066e5R262 - could you also ensure the `origin` is added to this newly vendored repo.

good catch, done

**Pull request merged**
