### PR TITLE
Support for ingesting user.domain

### LINKED ISSUE #5064: Support for user.domain
ECS has a field user.domain. Can we please add support for ingesting this field?

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Motivation/summary
Fixes #5064

## Checklist
- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [x] Documentation has been updated

## How to test these changes
There are tests for the new field

## Related issues
#5064

### CODE REVIEW

**Review by axw — COMMENTED** [review]
This looks great, thank you @tobiasstadler!

The tests are failing in `model/modeldecoder/rumv3`, because it doesn't set the new field. Can you please either:
 - duplicate the code you added to modeldecoder/v2 in modeldecoder/rumv3
 - update the tests to add "User.Domain" as an exception

If you take the first option (that would be my preference, but up to you), please change the json tag from "domain" to "ud" in the rumv3 package.

**Comment by tobiasstadler** [comment]
@axw I fixed the tests and the merge conflict

**Review by axw — APPROVED** [review]
Lovely, thank you :)

**Comment by axw** [comment]
@tobiasstadler looks like there's a formatting issue. CI is complaining:

> [2021-04-12T07:45:07.028Z] goimports differs:
> [2021-04-12T07:45:07.028Z]  - model/user_test.go

You should be able to fix this by running `make fmt`

**Comment by axw** [comment]
@tobiasstadler now there's a new issue: the RUMv3 additions require another `make update`.

**Comment by axw** [comment]
Please let me know if you'd like me to push fixes to your branch (if maintainer push access is enabled) - I'm happy to take care of these issues.

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by axw** [comment]
Tested with 7.13.0-100107e6, with canned data (intake-v2/transactions.ndjson) works well.

image

**Pull request merged**
