### PR TITLE
Update beats 20220104124402

### PR DESCRIPTION
**Pull request by v1v**
### What

Update dependencies and fix the go1.16 errors with some dependencies

1) `.ci/scripts/update-beats.sh`
2) `go mod tidy -go=1.16 && go mod tidy -go=1.17`
3) `.ci/scripts/update-beats.sh`
4) revert mage v1.12.1 to v1.11.0

### Issue

Closes https://github.com/elastic/apm-server/issues/6982

### CODE REVIEW

**Comment by v1v** [comment]
```
2022-01-04T13:26:11.068Z] warning: encountered multiple modules and could not deduce targeted Go version
[2022-01-04T13:26:49.819Z] beater/jaeger/grpc_test.go:261:46: grpc.WithInsecure is deprecated: use insecure.NewCredentials() instead. Will be supported throughout 1.x.  (SA1019)
[2022-01-04T13:26:49.819Z] beater/otlp/grpc_test.go:195:46: grpc.WithInsecure is deprecated: use insecure.NewCredentials() instead. Will be supported throughout 1.x.  (SA1019)
[2022-01-04T13:26:49.819Z] beater/server_test.go:407:39: grpc.WithInsecure is deprecated: use insecure.NewCredentials() instead. Will be supported throughout 1.x.  (SA1019)
[2022-01-04T13:26:49.819Z] beater/server_test.go:437:39: grpc.WithInsecure is deprecated: use insecure.NewCredentials() instead. Will be supported throughout 1.x.  (SA1019)
[2022-01-04T13:26:49.820Z] Makefile:158: recipe for target 'staticcheck' failed
[2022-01-04T13:26:49.820Z] make: *** [staticcheck] Error 1
[2022-01-04T13:26:49.820Z] + cleanup
[2022-01-04T13:26:49.820Z] + rm -rf /tmp/tmp.LPJrBiAmFj
script returned exit code 2
```

@elastic/apm-server , I might need your assistance with the above error 🙏

**Comment by axw** [comment]
I'll look into the errors.

**Review by axw — APPROVED** [review]

**Comment by v1v** [comment]
@axw 🙇 

BTW, I didn't add any backport label, so I don't know if it's needed, in case I need to add those labels please let me know 🙏

**Comment by axw** [comment]
No need to add labels for this one. We'll probably need to manually backport the changes if/when the other beats branches have been updated.

**Pull request merged**
