### PR TITLE
Document all the APIs

### PR DESCRIPTION
**Pull request by bmorelli25**
preview link: https://apm-server_11592.docs-preview.app.elstc.co/guide/en/apm/guide/master/api.html

Closes https://github.com/elastic/apm-server/issues/11066.

### CODE REVIEW

**Comment by bmorelli25** [comment]
@axw here's my start to closing https://github.com/elastic/apm-server/issues/11066.

For Elastic API endpoints, we document a sample request and response. For the Elastic intake API, we also document errors and their potential causes. Is that the level of detail you'd like to see for our Jaeger and OTel endpoints as well?

**Comment by axw** [comment]
@bmorelli25 thanks, I think this looks like enough for now. I wouldn't spend a lot of time on the Jaeger endpoints, OTLP is much more important. It's kinda hard to describe a request/response as it's all protobuf - I'd say that linking to the spec, as you've done, is good enough.

**Comment by bmorelli25** [comment]
Thanks, @axw. In that case, this PR is ready for review and merging if all looks good.

**Review by axw — APPROVED** [review]
LGTM, thanks @bmorelli25! Will go ahead and merge.

**Pull request merged**
