### PR TITLE
[7.11] Update to elastic/beats@b1e32c1925af

### PR DESCRIPTION
**Pull request by simitt**
## Motivation/summary
Update to elastic/beats@b1e32c1925af

### CODE REVIEW

**Comment by jalvz** [comment]
needs to update version in approved files

**Comment by simitt** [comment]
depends on https://github.com/elastic/apm-server/pull/4646

**Comment by simitt** [comment]
> needs to update version in approved files

@jalvz there has not been any version update - this is purely to bring in the latest beats fixes.

**Comment by jalvz** [comment]
there must be something else wrong in approvals then: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-4639/3/tests

**Comment by simitt** [comment]
Good catch @jalvz . The issue is that the Makefile still refered to `beats/7.x` instead of `beats/7.11`.

The last beats update was run on [Dec 16th](https://github.com/elastic/apm-server/pull/4547) from the `7.x` branch right before branching out the `7.11` branch. Therefore no changes that did not make it into `beats 7.11` should have been in this update. I don't believe we need to manually retest any APM Server functionality with this update.

**Review by jalvz — APPROVED** [review]

**Pull request merged**
