### PR TITLE
require clean golint

### LINKED ISSUE #2221: [golint] Add linter support
Either fix all `golint` issues once and then add `golint` to Intake CI stage, or add something like [houndci](https://houndci.com/) to github PRs.

### PR DESCRIPTION
**Pull request by graphaelli**
The first run should fail due to intentional introduction of lint failure, expecting:

```
 make check-full
...
.../github.com/elastic/apm-server/utility/data_fetcher.go:275:1: exported function FooBar should have comment or be unexported
make: *** [golint] Error 1
```

closes elastic/apm-server#2221

### CODE REVIEW

**Comment by graphaelli** [comment]
Right, intake step shows:

```
[2019-05-31T21:51:38.318Z] reviewdog: fail to get diff: exit status 128
```

but just continues right on.  I'm guessing `master` doesn't exist on CI during pr checks but will have to investigate more still.

**Comment by graphaelli** [comment]
I've given it one more shot that I think will work for CI but will require local users to have a remote named `origin` - I think that's reasonable but let me know if you disagree

**Comment by graphaelli** [comment]
Success

```
[2019-06-03T12:13:48.602Z] /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-2232/src/github.com/elastic/apm-server/utility/data_fetcher.go:275:1: exported function FooBar should have comment or be unexported

[2019-06-03T12:13:48.602Z] Makefile:108: recipe for target 'golint' failed
```

> I'd expect people to have a default remote configuration along the lines of `origin` pointing to the fork and `upstream` or `elastic` pointing to the original repository

Good point, I stuck `origin` in there to make it work with CI - we'd have to rename / add an origin to use something else there.  I'm not sure what impact renaming would have on the rest of CI so I think it's reasonable to require that our local `origin/master` is up to date with upstream for the sake of reproducing CI failures for this.  

I'll wait for your input before pushing up a revert of the intentional failure here.

**Comment by simitt** [comment]
nitpick: could you introduce an env_var for the remote name and set it to `origin` by default? This would give every dev the opportunity to have the ENV var set to something else, and no manual changes or updates or whatsoever would be required.

**Comment by graphaelli** [comment]
love that idea, doing it now

**Comment by graphaelli** [comment]
no pain at all, really happy with where we ended up

**Comment by graphaelli** [comment]
jenkins, run the tests please

**Comment by graphaelli** [comment]
tests failed on kibana sync, intake ✅

**Pull request merged**
