### PR TITLE
Multiple queues in the publisher

### PR DESCRIPTION
**Pull request by jalvz**
This attempts to explore https://github.com/elastic/apm-server/issues/947

Made some measurements in GCP, variance is quite high so take the results with a grain of salt. For the tables bellow I selected results falling in the middle.
This approach prioritizes transactions over errors, overall performance respect to master seems better with `concurrent_requests = 5` (default) but is not so clear with `concurrent_requests = 10`.

There are many more variables untested (other relevant settings like`mem.queue.events`, other values for `concurrent_requests`, other workload patterns, etc.). Given the variability of the results and the amount of knobs we have, exhaustive testing is not really doable.
This code is also more complex (and adds another knob to the mix) so I am reluctant to go with this. 
Happy to see alternative implementations.

Besides, I found that the best runs with `concurrent_requests=10` are much better than the best runs with the default, and with a similar memory usage. Did that has been observed/tested before?

______

- duration of each test = 1min
- transactions payload = ~900kb, 3 workers
- errors payload = ~200kb, 10 workers
- first table: `concurrent_requests=5`, second table: `concurrent_requests=10`
- for each table: first column is `master`, and second is this branch.
- for each table: first row is transactions only, and second row is transactions + errors.

- things to notice: latency and ratio of 503's between rows and columns - as expected ratio of 503's between errors and transactions is higher in this branch.

```
http://localhost:8200/v1/transactions
pushed 3.4Mb / sec , accepted 2.1Mb / sec        pushed 3.5Mb / sec , accepted 2.7Mb / sec
  [202] 139 responses (60.96%)                     [202] 182 responses (76.79%)
  [503] 89 responses (39.04%)                      [503] 55 responses (23.21%)
  total 228 responses (3.80 rps)                   total 237 responses (3.95 rps)
  431.66 ms / request                              329.67 ms / request
396.5Mb (max RSS)                                377.8Mb (max RSS)


http://localhost:8200/v1/transactions
pushed 3.3Mb / sec , accepted 1.9Mb / sec        pushed 3.6Mb / sec , accepted 2.7Mb / sec
  [202] 126 responses (56.00%)                     [202] 183 responses (75.31%)
  [503] 99 responses (44.00%)                      [503] 60 responses (24.69%)
  total 225 responses (3.75 rps)                   total 243 responses (4.05 rps)
  476.19 ms / request                              327.87 ms / request
http://localhost:8200/v1/errors
pushed 1.0Mb / sec , accepted 496.7kb / sec      pushed 1.0Mb / sec , accepted 485.6kb / sec
  [202]	134 responses (47.02%)                     [202] 131 responses (46.45%)
  [503]	151 responses (52.98%)                     [503] 151 responses (53.55%)
  total	285 responses (5.70 rps)                   total 282 responses (5.64 rps)
  373.14 ms / request                              381.68 ms / request
445.0Mb (max RSS)                                463.8Mb (max RSS)                        
```

```
http://localhost:8200/v1/transactions
pushed 3.4Mb / sec , accepted 2.1Mb / sec        pushed 3.4Mb / sec , accepted 2.3Mb / sec
  [202] 140 responses (61.40%)                     [202] 156 responses (67.24%) 
  [503] 88 responses (38.60%)                      [503] 76 responses (32.76%) 
  total 228 responses (3.80 rps)                   total 232 responses (3.87 rps) 
  428.57 ms / request                              384.62 ms / request
421.3Mb (max RSS)                                426.6Mb (max RSS)


http://localhost:8200/v1/transactions
pushed 3.3Mb / sec , accepted 1.8Mb / sec        pushed 3.4Mb / sec , accepted 1.9Mb / sec 
  [202] 119 responses (53.85%)                     [202] 128 responses (56.14%)
  [503] 102 responses (46.15%)                     [503] 100 responses (43.86%)
  total 221 responses (3.68 rps)                   total 228 responses (3.80 rps)
  504.24 ms / request                              468.75 ms / request
http://localhost:8200/v1/errors
pushed 1.9Mb / sec , accepted 630.1kb / sec      pushed 1.8Mb / sec , accepted 215.0kb / sec
  [202] 170 responses (32.88%)                     [202] 58 responses (11.72%)
  [503] 347 responses (67.12%)                     [503] 437 responses (88.28%) 
  total 517 responses (10.34 rps)                  total 495 responses (9.90 rps)
  294.14 ms / request                              862.09 ms / request
456.4Mb (max RSS)                                461.0Mb (max RSS)
```

### CODE REVIEW

**Comment by jalvz** [comment]
Ah, sorry, I didn't know you had that in mind. Then this comment https://github.com/elastic/apm-server/issues/947#issuecomment-395413333 makes more sense (i think).

If the goal is to prioritize transactions over errors, it _looks_ that this does the job - as per tables above:
`master`: `44.00%` `503`'s in transactions / `52.98%` in errors
this branch: `24.69%` `503`'s in transactions / `53.55%` in errors

`master`: `46.15%` `503`'s in transactions / `67.12%` in errors
this branch: `43.86%` `503`'s in transactions / `88.28%` in errors.

So this branch accepts >2X more transactions than errors (for these tests), which was the intention.
My point is that it is more complicated, hard to test and hard to prove how/if it helps users after all.

I don't mind trying out different clients, but that seems even more complicated and I don't understand why should be better - at the end is the same elasticsearch cluster with the same ingestion capacity, same network, etc.

**Comment by simitt** [comment]
Maybe I misunderstand the purpose of the PR, so I elaborate a bit on my thoughts:
I don't think that prioritising transactions over errors or the other way around should be the goal here. Instead we want to avoid reducing the ingestion rate for transactions if error rate suddenly increases (and the other way around). When sharing one internal libbeat queue, that has a max size it is likely that in the event of a sudden increase of documents for one doc type the ingestion rate for the other doc types decreases, as the queue size is limited. When having a separate client per type, where every client has its own queue a sudden increase of documents e.g. errors would fill up the error queue, so errors would start getting dropped. But transactions could be processed normally.

Now I agree that if we generally overload the ES ingestion, transactions and errors would still not be isolated from each other, but that's why we have a max queue size to prevent this.

**Comment by jalvz** [comment]
Some more data:
Top graph shows a constant rate of transactions (15/sec) and how we drop them when the apm-server is overloaded with errors. Bottom graph shows the corresponding error count.

It more or less matches my expectations. @simitt @graphaelli does it make sense to you? 
Any other scenarios you think should be tested?

transactions-annotated
errors

**Comment by graphaelli** [comment]
After clarifying with @jalvz, the results make sense to me.  The top row is the number of transactions ingested, the bottom is the number of errors.   Each column is the result of applying a massive error spike on top of a constant 15/s transaction load against difference branches/configs.

I like the idea of allowing users to specify a preference for dropping transactions or errors (or metrics ..) in the face of memory exhaustion, depending on their needs.  I'm struggling with allocating fixed sized queues for this purpose, and exposing such specific tunables to accomplish that.

Why should apm-server drop errors when there's plenty of memory to handle them otherwise?  Does this problem go away completely with a disk-backed queue?  Does moving to 1 transaction per request, like errors are in practice, change this into strictly a rate limiting problem?

**Comment by jalvz** [comment]
I am very biased by my experience, but I don't see a lot of value in ingesting 200 errors per minute instead of 100, when all are the same. 

Since how little difference is between 0.8 transactions - 0.2 queues; and 0.5 each (3rd and 4th blocks) I would spare customers another config option and just hardcode a ratio.

**Comment by jalvz** [comment]
I tried to use several clients and It doesn't work. I believe it is because `beat.Pipeline` is a stateful object and I can't get more than 1 client out of it. I only get one beat.Pipeline from the `beat.Beat`.

My attempt is here: https://github.com/elastic/apm-server/compare/master...jalvz:multiple-clients?expand=1

Is there something obviously wrong there? Any other ideas?

**Comment by simitt** [comment]
Your implementation generally LGTM - that's basically what I meant to separate the two clients. When `beat.Pipeline` only allows for 1 client and you don't see an improvement on isolating transactions and errors from each other with this approach, I agree that it doesn't make too much sense.

**Comment by jalvz** [comment]
Closing this to explore https://github.com/elastic/apm-server/issues/1057 first.

**Pull request closed without merging**
