### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by bZichett**
## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [x] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [x] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by axw** [comment]
Thanks @bZichett! Would you please [sign the CLA](https://www.elastic.co/contributor-agreement)? We can't accept changes without that. If you would prefer, we can make the fix instead.

**Comment by bZichett** [comment]
@axw: You should see my CLA submission now. 

I'd like to be able to contribute in the future, so although this change is a no-op, curious to just get this step out of the way.

**Review by axw — APPROVED** [review]
Thanks @bZichett :)

**Pull request merged**
