### PR TITLE
Remove unused cruft from the repo

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

- Dockerfile was used for testing in the past, but not any more
- .dockerignore file is related to the above
- .backportrc.json is outdated, and we have been using Mergify for creating backports for a while now.
- .editorconfig looks like new-repo boilerplate. I don't think it's needed, but happy to here arguments for keeping it.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

N/A

## Related issues

None

### CODE REVIEW

**Review by lahsivjar — APPROVED** [review]
LGTM. Personally, I have not used `editorconfig` in the past but it sounds useful.

**Review by simitt — APPROVED** [review]
+1 on removing all these, also haven't used `.editorconfig`

**Comment by axw** [comment]
> Personally, I have not used editorconfig in the past but it sounds useful.

:+1: If it turns out it's useful, we can add it back in.

**Comment by Mpdreamz** [comment]
As a [board member for editrorconfig](https://github.com/orgs/editorconfig/teams/board-member/members) I'm not sure I can allow its deletion :smile_cat: 

In all seriousness most editors automatically pick it up and ensure consistent formatting. You might be using it without knowing!

**Comment by axw** [comment]
@Mpdreamz yeah the thought crossed my mind that we've been benefiting from it without knowing. I'm going to delete it anyway, and we'll see what the fallout is. Most Go devs use automatic Go formatting, and we check this in CI; so I think it may be redundant in our case.

**Comment by axw** [comment]
Build failed because OSX VMs aren't coming up, reported and merging anyway.

**Comment by Mpdreamz** [comment]
I think the value comes from editing non go code (yaml, json, py) to ensure everyone's editors use the same line endings and indentation (width/style). 

Another benefit is that GitHub itself is editorconfig aware and uses it when displaying code. 

I'll leave the decision with the team but `.editorconfig` files are definitely very handy!

**Pull request merged**
