### PR TITLE
docs: Source AWS Lambda extension docs from repo

### PR DESCRIPTION
**Pull request by bmorelli25**
### Summary

Sources AWS Lambda extension docs from the [elastic/apm-aws-lambda](https://github.com/elastic/apm-aws-lambda) repo instead of copy/pasting them.

Closes https://github.com/elastic/observability-docs/issues/1132.

### Note

The new command to build the APM Guide docs is:

```
 $GIT_HOME/docs/build_docs --doc $GIT_HOME/apm-server/docs/integrations-index.asciidoc --resource=$GIT_HOME/observability-docs/ --resource=$GIT_HOME/apm-aws-lambda/ --chunk 2 --open
```

### CODE REVIEW

**Comment by bmorelli25** [comment]
@astorm — apologies that this took so long. The only thing left is to create 8.0, 7.17, and 7.16 branches in the apm-aws-lamda repo and to backport the docs directory to those branches. I can take care of this if you'd like!

**Review by dedemorton — APPROVED** [review]
LGTM. Looks like you just need to update the branch.

**Comment by astorm** [comment]
Thanks @bmorelli25!  Re: 

> The only thing left is to create 8.0, 7.17, and 7.16 branches in the apm-aws-lamda repo and to backport the docs directory to those branches. I can take care of this if you'd like!

Yes, if you could do and that, as well as capture what was done somewhere so we can do it for future releases, that would be great.

**Review by astorm — APPROVED** [review]
👍

**Pull request merged**
