### PR TITLE
systemtest: Fix geoip changes

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

Fix geoip changes that cause systemtest failures

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by dmathieu** [comment]
Do we know why those geoip values have changed?

**Comment by carsonip** [comment]
> Do we know why those geoip values have changed?

Didn't dig into it but my guess is that the geoip db used by ES is updated. Something similar happened in the past.

**Review by dmathieu — APPROVED** [review]

**Comment by carsonip** [comment]
- This will need to be backported to active dev branches.
- I'm thinking if it is better to ignore `client.geo` so that we don't have to go through this if geoip db changes frequently.

**Comment by carsonip** [comment]
@Mergifyio backport 8.11

**Pull request merged**
