### PR TITLE
docs/spec: fix JSON Schema for arrays of objects

### LINKED ISSUE #4515: stacktrace property in v2 error spec should list properties under items property
The properties of each frame in a `stacktrace` are listed as properties of the `stacktrace`:

https://github.com/elastic/apm-server/blob/be85ba7e0e869871db9d49570392b6f354ef3b7d/docs/spec/v2/error.json#L635-L734

It looks like these  should be listed as properties of the items schema (the frames) of a `stacktrace` i.e.

```json
"stacktrace": {
    "description": "Stacktrace information of the captured exception.",
    "type": [
        "null",
        "array"
    ],
    "items": {
        "type": "object",
        "properties": {
            "abs_path": {
                "description": "AbsPath is the absolute path of the frame's file.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "classname": {
                "description": "Classname of the frame.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "colno": {
                "description": "ColumnNumber of the frame.",
                "type": [
                    "null",
                    "integer"
                ]
            },
            "context_line": {
                "description": "ContextLine is the line from the frame's file.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "filename": {
                "description": "Filename is the relative name of the frame's file.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "function": {
                "description": "Function represented by the frame.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "library_frame": {
                "description": "LibraryFrame indicates whether the frame is from a third party library.",
                "type": [
                    "null",
                    "boolean"
                ]
            },
            "lineno": {
                "description": "LineNumber of the frame.",
                "type": [
                    "null",
                    "integer"
                ]
            },
            "module": {
                "description": "Module to which the frame belongs to.",
                "type": [
                    "null",
                    "string"
                ]
            },
            "post_context": {
                "description": "PostContext is a slice of code lines immediately before the line from the frame's file.",
                "type": [
                    "null",
                    "array"
                ],
                "items": {
                    "type": "string"
                },
                "minItems": 0
            },
            "pre_context": {
                "description": "PreContext is a slice of code lines immediately after the line from the frame's file.",
                "type": [
                    "null",
                    "array"
                ],
                "items": {
                    "type": "string"
                },
                "minItems": 0
            },
            "vars": {
                "description": "Vars is a flat mapping of local variables of the frame.",
                "type": [
                    "null",
                    "object"
                ]
            }
        },
        "anyOf": [
            {
                "properties": {
                    "classname": {
                        "type": "string"
                    }
                },
                "required": [
                    "classname"
                ]
            },
            {
                "properties": {
                    "filename": {
                        "type": "string"
                    }
                },
                "required": [
                    "filename"
                ]
            }
        ]
    },
    "minItems": 0
},
```

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

The properties for array items should be tested under "items", not added directly to the array object.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
~- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~

I have considered changes for:
~- [ ] documentation~
~- [ ] logging (add log lines, choose appropriate log selector, etc.)~
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))~
- [x] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
~- [ ] telemetry~
~- [ ] Elasticsearch Service (https://cloud.elastic.co)~
~- [ ] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)~
~- [ ] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)~

## How to test these changes

???
Talk to @russcam 

## Related issues

Closes #4515

### CODE REVIEW

**Review by simitt — APPROVED** [review]
Thanks for the fix, completely overlooked that!

**Comment by russcam** [comment]
It looks like some of the properties are missing a `"type"`:

- `"experimental"` on transaction:

   https://github.com/axw/apm-server/blob/c06bccdaaec6daf63bb63008998269f18873f2b9/docs/spec/v2/transaction.json#L19-L21

- `"experimental"` on span:

   https://github.com/axw/apm-server/blob/c06bccdaaec6daf63bb63008998269f18873f2b9/docs/spec/v2/span.json#L137-L139

- `"experimental"` on error:

   https://github.com/axw/apm-server/blob/c06bccdaaec6daf63bb63008998269f18873f2b9/docs/spec/v2/error.json#L20-L22

Looking at the structs, these are [`interface {}`](https://github.com/axw/apm-server/blob/c06bccdaaec6daf63bb63008998269f18873f2b9/model/error.go#L80). Should these be part of the schema?

**Comment by axw** [comment]
@russcam that is expected. `interface{}` is like an "any" type; there are no restrictions on the type.

**Comment by russcam** [comment]
> @russcam that is expected. interface{} is like an "any" type; there are no restrictions on the type.

Gotcha!

**Review by russcam — APPROVED** [review]
LGTM, thanks @axw 👍

**Comment by axw** [comment]
Unrelated test failure -- https://github.com/elastic/apm-server/issues/4366

**Pull request merged**
