### PR TITLE
Rename service metrics to service transaction metrics

### LINKED ISSUE #9654: service metrics: extend to non-transaction events and add zero counts
Service metrics should also be produced when application metrics, errors & logs for a service are observed. When during an aggregation period no transaction events are seen for this service, then a zero count for transaction throughput needs to be stored with the service metric.

### PR DESCRIPTION
**Pull request by carsonip**
## Motivation/summary

Rename service metrics to service transaction metrics, including all internal and external usages.

External facing changes:
- data stream name change: `metrics-apm.service-${interval}` -> `metrics-apm.service_transaction-${interval}`
- field name change: `service.aggregation.overflow_count` -> `service_transaction.aggregation.overflow_count`
- metricset name change: `service` -> `service_transaction`
- config field name `apm-server.aggregation.service` -> `apm-server.aggregation.service_transactions`

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [x] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [x] Documentation has been updated

## How to test these changes

N/A

## Related issues

Part of #9654
Closes #9654

### CODE REVIEW

**Review by simitt — APPROVED** [review]
LGTM, please wait for confirmation from the UI team before merging.

**Comment by carsonip** [comment]
@dgieselaar @sqren This renaming PR should be replacing all occurrences of service metrics related names to service transaction metrics. And this will require corresponding changes on the UI side. What do you think about this change?

External facing changes include:
- data stream name change: `metrics-apm.service-${interval}` -> `metrics-apm.service_transaction-${interval}`
- field name change: `service.aggregation.overflow_count` -> `service_transaction.aggregation.overflow_count`
- metricset name change: `service` -> `service_transaction`
- config field name `apm-server.aggregation.service` -> `apm-server.aggregation.service_transactions`

cc @simitt

**Comment by dgieselaar** [comment]
@carsonip lgtm. Does the field name impact anything else? I think we have a policy setting related to the recording of service metrics

**Comment by carsonip** [comment]
> @carsonip lgtm. Does the field name impact anything else? I think we have a policy setting related to the recording of service metrics

Hmm I'm not aware of that. What policy are we talking about? @simitt do you have any idea?

**Comment by simitt** [comment]
@dgieselaar do you mean the setting in the Fleet UI to enable/disable it?

**Comment by dgieselaar** [comment]
@simitt yes

**Comment by simitt** [comment]
Sounds good, that's basically why we pinged you. Can you trigger the changes on the UI side? We are going to merge this PR in then.

**Comment by dgieselaar** [comment]
@simitt what kind of changes would that be? I am not sure how a settings key gets translated to an APM Server config setting. @sqren do you know?

**Comment by sqren** [comment]
> I am not sure how a settings key gets translated to an APM Server config setting. @sqren do you know?

Not from the top of my head, no.

**Comment by carsonip** [comment]
@simitt I'm not sure if I completely understand the convo above. Did @dgieselaar want to know impact of the config key change, but our understanding is that in reality that config was never exposed in the UI anyway? Is that right?

**Comment by dgieselaar** [comment]
@carsonip looks like the key and its interpretation is entirely in APM Server, so no concerns from me: https://github.com/search?q=org%3Aelastic+service_metrics_enabled&type=code

**Comment by carsonip** [comment]
> @carsonip looks like the key and its interpretation is entirely in APM Server, so no concerns from me: https://github.com/search?q=org%3Aelastic+service_metrics_enabled&type=code

I believe you actually found something that we should remove. That option is no longer useful and service (transaction) metrics is always enabled since https://github.com/elastic/apm-server/issues/10048. I'll go ahead and remove that from apmpackage. Thanks!

**Comment by simitt** [comment]
@carsonip the PR is good to merge then once all checks are green.

**Pull request merged**
