### PR TITLE
update agent_config examples

### PR DESCRIPTION
**Pull request by stuartnelson3**
## Motivation/summary

The values are being rendered as strings in kibana
and internally represented as strings anyway, so
we should be consistent

mentioned [here](https://github.com/elastic/kibana/pull/100744#issuecomment-850037068)

## Checklist

- [x] Documentation has been updated

## How to test these changes

Non-functional change.

### CODE REVIEW

**Review by axw — APPROVED** [review]
Maybe explicitly quote them all? IIANM, YAML will treat each of `off`, `false`, and `true` as booleans. That just leaves `info` as a string, so it's probably clearer just to quote them all at that point.

**Comment by stuartnelson3** [comment]
After our discussion in stand-up, we decided to remove the `agent_config` section entirely, correct? @simitt @axw

**Comment by axw** [comment]
Yes, let's just remove the example from apm-server.yml for now. Maybe it can come back later.

**Comment by stuartnelson3** [comment]
Closed in favor of https://github.com/elastic/apm-server/pull/5366

**Pull request closed without merging**
