### PR TITLE
Check if Kibana files are up-to-date

### PR DESCRIPTION
**Pull request by simitt**
APM dashboards and index pattern are stored in Kibana. Add test to
ensure that those files are kept up-to-date.

implements elastic/apm-server#1042 

Current Differences found by this script:
```
---- Comparing Dashboards
================================
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=1.params.customLabel'
"Avg. Resp. Time"
Value in APM Server: Avg. Trans. Time
Value in Kibana: Avg. Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=3.params.customLabel'
"Resp. Time"
Value in APM Server: Trans. Time
Value in Kibana: Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Top Services by Response Time [APM]"
Value in APM Server: Top Services by Transaction Time [APM]
Value in Kibana: Top Services by Response Time [APM]
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Top Services by Response Time [APM]"
Value in APM Server: Top Services by Transaction Time [APM]
Value in Kibana: Top Services by Response Time [APM]
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.value_template'
"{{value}} rpm"
Value in APM Server: {{value}} tpm
Value in Kibana: {{value}} rpm
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Top Apps by Request Per Minute [APM]"
Value in APM Server: Top Apps by Transaction Per Minute [APM]
Value in Kibana: Top Apps by Request Per Minute [APM]
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Top Services by Request Per Minute [APM]"
Value in APM Server: Top Services by Transaction Per Minute [APM]
Value in Kibana: Top Services by Request Per Minute [APM]
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'c618e4e0-7c69-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'ceefd050-7c6a-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.filter.query={u'match': {u'processor.event': {u'query': u'error', u'type': u'phrase'}}}.meta.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'ceefd050-7c6a-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '22518e70-7c69-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'a2e199b0-7820-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Response Times [APM]"
Value in APM Server: Transaction Times [APM]
Value in Kibana: Response Times [APM]
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Response Times [APM]"
Value in APM Server: Transaction Times [APM]
Value in Kibana: Response Times [APM]
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.value_template'
"{{value}} rpm"
Value in APM Server: {{value}} tpm
Value in Kibana: {{value}} rpm
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.metrics.id=61ca57f2-469d-11e7-af02-69e470af7417.type'
"count"
Value in APM Server: cardinality
Value in Kibana: count
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.split_mode'
"terms"
Value in APM Server: everything
Value in Kibana: terms
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.show_legend'
1
Value in APM Server: 0
Value in Kibana: 1
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Request Per Minute [APM]"
Value in APM Server: Transaction Per Minute [APM]
Value in Kibana: Request Per Minute [APM]
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Request Per Minute [APM]"
Value in APM Server: Transaction Per Minute [APM]
Value in Kibana: Request Per Minute [APM]
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'd7735b90-7ddf-11e7-b115-df9c90da2df1' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.filter.query={u'match': {u'processor.event': {u'query': u'span', u'type': u'phrase'}}}.meta.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'd7735b90-7ddf-11e7-b115-df9c90da2df1' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
---- Comparing Index Pattern
================================
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_id.searchable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_id.aggregatable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_index.searchable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_index.aggregatable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'id'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
make: *** [are-kibana-objects-updated] Error 2
```

### CODE REVIEW

**Comment by jalvz** [comment]
`make are-kibana-objects-updated master`
gives me
```
---- Comparing Dashboards
================================
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=1.params.customLabel'
"Avg. Resp. Time"
Value in APM Server: Avg. Trans. Time
Value in Kibana: Avg. Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=3.params.customLabel'
"Resp. Time"
Value in APM Server: Trans. Time
Value in Kibana: Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Top Services by Response Time [APM]"
Value in APM Server: Top Services by Transaction Time [APM]
Value in Kibana: Top Services by Response Time [APM]
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Top Services by Response Time [APM]"
Value in APM Server: Top Services by Transaction Time [APM]
Value in Kibana: Top Services by Response Time [APM]
---
Difference for id '1bdca740-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.value_template'
"{{value}} rpm"
Value in APM Server: {{value}} tpm
Value in Kibana: {{value}} rpm
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Top Apps by Request Per Minute [APM]"
Value in APM Server: Top Apps by Transaction Per Minute [APM]
Value in Kibana: Top Apps by Request Per Minute [APM]
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Top Services by Request Per Minute [APM]"
Value in APM Server: Top Services by Transaction Per Minute [APM]
Value in Kibana: Top Services by Request Per Minute [APM]
---
Difference for id '804ffc40-7828-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'c618e4e0-7c69-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'ceefd050-7c6a-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.filter.query={u'match': {u'processor.event': {u'query': u'error', u'type': u'phrase'}}}.meta.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'ceefd050-7c6a-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '22518e70-7c69-11e7-aa55-3b0d52c71c60' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'a2e199b0-7820-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Response Times [APM]"
Value in APM Server: Transaction Times [APM]
Value in Kibana: Response Times [APM]
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Response Times [APM]"
Value in APM Server: Transaction Times [APM]
Value in Kibana: Response Times [APM]
---
Difference for id '09bcf890-7822-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.value_template'
"{{value}} rpm"
Value in APM Server: {{value}} tpm
Value in Kibana: {{value}} rpm
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.metrics.id=61ca57f2-469d-11e7-af02-69e470af7417.type'
"count"
Value in APM Server: cardinality
Value in Kibana: count
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.series.id=61ca57f1-469d-11e7-af02-69e470af7417.split_mode'
"terms"
Value in APM Server: everything
Value in Kibana: terms
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.params.show_legend'
1
Value in APM Server: 0
Value in Kibana: 1
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.title'
"Request Per Minute [APM]"
Value in APM Server: Transaction Per Minute [APM]
Value in Kibana: Request Per Minute [APM]
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.title'
"Request Per Minute [APM]"
Value in APM Server: Transaction Per Minute [APM]
Value in Kibana: Request Per Minute [APM]
---
Difference for id '55606a60-7823-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'd7735b90-7ddf-11e7-b115-df9c90da2df1' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.filter.query={u'match': {u'processor.event': {u'query': u'span', u'type': u'phrase'}}}.meta.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
Difference for id 'd7735b90-7ddf-11e7-b115-df9c90da2df1' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
---- Comparing Index Pattern
================================
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_id.searchable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_id.aggregatable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_index.searchable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'attributes.fields.name=_index.aggregatable'
true
Value in APM Server: False
Value in Kibana: True
---
Difference for id '12e52550-6354-11e8-9d01-ed6a4badd083' for key 'id'
"12e52550-6354-11e8-9d01-ed6a4badd083"
Value in APM Server: apm-*
Value in Kibana: 12e52550-6354-11e8-9d01-ed6a4badd083
---
make: *** [are-kibana-objects-updated] Error 2
```

Is this expected?

**Comment by simitt** [comment]
I am planning on opening a PR for Infra that runs this test on every PR, once we have figured out how to make this test successful (excluding parts of the test or aligning the files).

**Comment by simitt** [comment]
cc @sqren and @makwarth

**Comment by sqren** [comment]
Awesome! Thanks for doing this @simitt !

**Comment by makwarth** [comment]
++ good job @simitt !

**Pull request merged**
