### PR TITLE
Move business logic out of model transformation

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Move some business logic out of model transformation
into model processors (hostname, node name) and decoder
(page.* -> url & http). This moves us closer to being
able to generate code for model transformation.

When decoding, copy `page.url` to `url` and `page.referer`
to `http.request.referrer`. By doing this in the decoder,
we avoid further enshrining the page fields on model types.

When decoding span-specific service metadata, overlay it on
the event's Metadata.Service field rather than creating a
separate field and merging at transformation time.

System.DetectedHostname, System.ConfiguredHostname, and
Service.Node.Name are now set by model processors. This
removes the need for the System.Hostname() method.

Many approvals have changed because they do not go through
the full beater pipeline. Importantly though, system tests
and beater integration tests have not changed.

## How to test these changes

Non-functional change.

## Related issues

https://github.com/elastic/apm-server/issues/3565

### CODE REVIEW

**Review by simitt — APPROVED** [review]
There's a lot going on in this PR, but great changes. I really like the `modelprocessors` you introduced.

**Comment by axw** [comment]
> There's a lot going on in this PR, but great changes.

Indeed, sorry about that - I'll try to better in the future. I started out making small PRs and then got a bit carried away in this one.

> I really like the modelprocessors you introduced.

Glad to hear it!

**Comment by axw** [comment]
Sorry about force-push, I merged badly and had to fix it.

**Comment by jalvz** [comment]
nothing to test here, let me know i missed something

**Comment by simitt** [comment]
@jalvz I was thinking of testing that the `hostname` information is still properly populated. Same applies to the `page.url` fields for which the refactoring has been applied.

**Pull request merged**
