### PR TITLE
Add a reason to some auth failures

### LINKED ISSUE #4880: [OpenTelemetry - Authentication] Ensure a helpful error message is returned for malformed Authorization header
When using the native OTLP intake and auth is enabled, we should ensure the server returns a helpful error message when the Authorization header is missing or invalid (without leaking information!) to assist the user in configuring the OpenTelemetry SDK or Collector.

Some test cases we should consider:

- "Authorisation: Bearer 123456" --> wrong header name (should be "Authorization")
- "Authorization: 123456" --> wrong value, forgot "Bearer" or "ApiKey"
- "Authorisation: Bearer" --> wrong value, forgot space token after "Bearer"

### LINKED ISSUE #5061: authorization: errors querying Elasticsearch for API Key auth result in 401 instead of 503
**APM Server version** (`apm-server version`):

7.12.0

**Description of the problem including expected versus actual behavior**:

When APM Server is configured with API Key auth and a non-auth related error occurs while querying Elasticsearch for privileges, APM Server responds `401 Unauthorized`. I would expect the server to respond with `503 Service Unavailable` instead.

**Steps to reproduce**:

 1. Run apm-server with `-E apm-server.api_key.enabled=true -E apm-server.api_key.elasticsearch.hosts=[testing.invalid:1234]`
 2. `curl -H "Authorization: ApiKey foo" -v http://localhost:8200/intake/v2/events` receives 401

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Add a reason to some auth failures, to better inform users of how to configure clients. The reasons we include are limited to:
 - invalid authorization kind, e.g. "Authorization: Bear token" instead of "Authorization: Bearer token"
 - missing or improperly formatted Authorization header, e.g. "Authorization: token" instead of "Authorization: Bearer token"

Most importantly, no details of the server's configuration are leaked. The auth failure reason is used to populate the error message sent back to clients, in both HTTP and gRPC requests.

There is also a change in this PR to return 503 Service Unavailable rather than 401 Unauthorized when an auth implementation returns an error. For example if Elasticsearch cannot be reached for API Key auth, that's a 503 and not 401. This addresses #5061.

Finally, there is some refactoring in this PR to make this all possible:
 - We introduce a `beater/authorization.Result` struct type, which holds a boolean indicating whether auth was successful, and an optional reason if not.
 - We no longer store a `beater/authorization.Authorization` on the request object, but instead store a Result.
 - The Authorization interface has been simplified, and the Deny/AllowAuth implementations have been unexported.

Later on we could look at extending the Result struct for storing auth-related information in documents as described in https://github.com/elastic/apm-server/issues/3731.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

1. Configure the server with a secret token, say "abc123"
2. Using curl, send a POST request to `/intake/v2/events` with:
  - no Authorization header: server should respond saying header is missing or badly formatted
  - a badly formatted Authorization header (`-H "Authorization: abc123"`): server should respond saying header is missing or badly formatted
  - an Authorization header with an invalid auth kind (`-H "Authorization: Secret Token"`): server should respond saying "Secret" is not a valid auth kind
  - an Authorization header with an invalid secret token (`-H "Authorization: Bearer Token"`): server should respond `unauthorized`
3. Run a subset of these tests an OpenTelemetry SDK, proving the OTLP/gRPC intake is also covered.

## Related issues

Closes #4880 
Closes #5061

### CODE REVIEW

**Review by simitt — APPROVED** [review]
LGTM and simplifies the code.

**Comment by axw** [comment]
System test failures are unrelated, will be fixed by https://github.com/elastic/apm-server/pull/5071

**Comment by stuartnelson3** [comment]
running with cURL was as expected:

>no Authorization header: server should respond saying header is missing or badly formatted
```
# curl -XPOST http://localhost:8200/intake/v2/events
{
  "error": "missing or improperly formatted Authorization header: expected 'Authorization: Bearer secret_token' or 'Authorization: ApiKey base64(API key ID:API key)'"
}
```
>a badly formatted Authorization header (-H "Authorization: abc123"): server should respond saying header is missing or badly formatted
```
# curl -XPOST http://localhost:8200/intake/v2/events -H "Authorization: abc123"
{
  "error": "missing or improperly formatted Authorization header: expected 'Authorization: Bearer secret_token' or 'Authorization: ApiKey base64(API key ID:API key)'"
}
```
>an Authorization header with an invalid auth kind (-H "Authorization: Secret Token"): server should respond saying "Secret" is not a valid auth kind
```
# curl -XPOST http://localhost:8200/intake/v2/events -H "Authorization: Secret Token"
{
  "error": "unknown Authorization kind Secret: expected 'Authorization: Bearer secret_token' or 'Authorization: ApiKey base64(API key ID:API key)'"
}
```
>an Authorization header with an invalid secret token (-H "Authorization: Bearer Token"): server should respond unauthorized
```
# curl -XPOST http://localhost:8200/intake/v2/events -H "Authorization: Bearer Token"
{
  "error": "unauthorized"
}
```
And, for funsies, making it past the auth middleware
```
# curl -XPOST http://localhost:8200/intake/v2/events -H "Authorization: Bearer abc123"
{
  "accepted": 0,
  "errors": [
    {
      "message": "invalid content type: ''"
    }
  ]
}
```

**Comment by stuartnelson3** [comment]
otlp:
log line errors from collector

no token
```
2021-05-05T07:13:05.121Z        error   exporterhelper/queued_retry.go:243      Exporting failed. Try enabling retry_on_failure config option.  {"kind": "exporter", "name": "elastic", "error": "request failed with 401 Unauthorized: {\"error\":\"missing or improperly formatted Authorization header: expected 'Authorization: Bearer secret_token' or 'Authorization: ApiKey base64(API key ID:API key)'\"}"}
```

bad token
```
2021-05-05T07:17:58.101Z        warn    batchprocessor/batch_processor.go:209   Sender failed   {"kind": "processor", "name": "batch", "error": "request failed with 401 Unauthorized: {\"error\":\"unauthorized\"}"}
```

**Pull request merged**
