### PR TITLE
docs: Fix the install-service.ps1 file name for windows

### PR DESCRIPTION
**Pull request by wonseop**
## Motivation/summary

After 8.5.0, the file name was changed from `install-service-apm-server.ps1` to `install-service.ps1`, but it was not modified in the document. The file name of the apm-server installation document for Windows has been corrected.

## Checklist

- [X] Documentation has been updated

### CODE REVIEW

**Review by carsonip — APPROVED** [review]

**Comment by carsonip** [comment]
Hi @wonseop , all commits are required to be signed. In the PR, the commit by @refarde is not signed. Is it possible for you / @refarde to get it signed in order to merge the PR? Thanks

**Review by refarde — APPROVED** [review]

**Comment by wonseop** [comment]
> Hi @wonseop , all commits are required to be signed. In the PR, the commit by @refarde is not signed. Is it possible for you / @refarde to get it signed in order to merge the PR? Thanks



> Hi @wonseop , all commits are required to be signed. In the PR, the commit by @refarde is not signed. Is it possible for you / @refarde to get it signed in order to merge the PR? Thanks

**Comment by wonseop** [comment]
I am so sorry. I accidentally closed the PR while operating it with my cell phone. It may be inconvenient, but please understand that we will do a new PR.

**Comment by wonseop** [comment]
> Hi @wonseop , all commits are required to be signed. In the PR, the commit by @refarde is not signed. Is it possible for you / @refarde to get it signed in order to merge the PR? Thanks

@refarde is my sub-account. Now I don't know how to sign that commit. If you wish, I will remove the PR and create a new PR so that all commits can be verified.

**Comment by carsonip** [comment]
@wonseop Feel free to create a new PR with signed commits. Thanks for going through the trouble.

**Comment by wonseop** [comment]
I'll close this PR and open a new one.

**Pull request closed without merging**
