### PR TITLE
Merge master into 6.0 branch

### PR DESCRIPTION
**Pull request by ruflin**
Please use merge for this PR.

### CODE REVIEW

**Comment by jalvz** [comment]
Ron wanted to backport a298a0d4039d7df6c854ab37fda5c540542b18a9 as well, and 52b48dc41d5deafb38ea29c8c87bae9cab3e0e8b is related to that.
Can you please incorporate those?

**Comment by ruflin** [comment]
@jalvz Definitively.

**Comment by roncohen** [comment]
@ruflin haven't checked, but looks like you're pinning to libbeat 7 here and removing the explicit version. This needs to come out as 6.0.0 in the end.

**Comment by ruflin** [comment]
@roncohen Where did you see this? Did a quick test locally and it is 6.0.0-rc1 as expected.

The failing tests will be fixed with https://github.com/elastic/beats/pull/5144/commits/23506f56e9fd532f067ad501c993a11ab5f438a3 in https://github.com/elastic/beats/pull/5144

**Comment by roncohen** [comment]
looks like you're right 👍

**Comment by ruflin** [comment]
Will update this PR again when https://github.com/elastic/beats/pull/5144 is in and then also get the most recent changes from @jalvz .

**Pull request merged**
