### PR TITLE
smoketest: Improve output, parallelize by test

### PR DESCRIPTION
**Pull request by marclop**
## Motivation/summary

Improves the smoke test output by redirecting all terraform commands to
a `tf.log` file, and changes the way the tests are discovered to allow
each test to run in parallel.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

1. `make smoketest/all SMOKETEST_VERSION=7.17,latest`
2. Verify the output is easily readable.

## Related issues

#8303

### CODE REVIEW

**Comment by marclop** [comment]
hm, the tests don't seem to be running in parallel as we expected, the Makefile targets result in a "nothing to do for target XYZ". @amannocci Do you know what we could be doing differently here so it runs as intended?

**Comment by amannocci** [comment]
I looked at the issue and it seems to be related to the `smoketest/discover` target.
It returns a single line with ' ' as a delimiter instead of a '\n' delimiter.

Let's try this :
```
.PHONY: smoketest/discover
smoketest/discover:
	@echo "$(SMOKETEST_DIRS)"
```

Instead of this :
```
.PHONY: smoketest/discover
smoketest/discover:
	@echo $(SMOKETEST_DIRS)
```

**Comment by amannocci** [comment]
Looks better : https://apm-ci.elastic.co/job/apm-server/job/smoke-tests-mbp/view/change-requests/job/PR-8638/3/

**Comment by simitt** [comment]
Results look wrong:
- all 3 jobs seem to try running the same test: `Running 7.17.5 standalone to 8.3.2 to 8.3.2 managed`
- only the first job passes, the other two show the error below
- the log states that the test failed ❌ but it is reported to have been successful ✅ 

```
[2022-07-19T10:13:08.337Z] + make smoketest/run TEST_DIR=/var/lib/jenkins/workspace/m-server_smoke-tests-mbp_PR-8638/src/github.com/elastic/apm-server/testing/smoke/legacy-standalone-major-managed

[2022-07-19T10:13:08.840Z] -> Running /var/lib/jenkins/workspace/m-server_smoke-tests-mbp_PR-8638/src/github.com/elastic/apm-server/testing/smoke/legacy-standalone-major-managed smoke tests for version 7.17...

[2022-07-19T10:13:09.044Z] -> Running 7.17.5 standalone to 8.3.2 to 8.3.2 managed

[2022-07-19T10:13:09.045Z] -> Creating / Upgrading deployment to version 7.17.5

[2022-07-19T10:13:12.557Z] 

[2022-07-19T10:13:12.557Z] Error: Required plugins are not installed

[2022-07-19T10:13:12.557Z] 

[2022-07-19T10:13:12.557Z] The installed provider plugins are not consistent with the packages selected

[2022-07-19T10:13:12.557Z] in the dependency lock file:

[2022-07-19T10:13:12.557Z]   - registry.terraform.io/hashicorp/local: the cached package for registry.terraform.io/hashicorp/local 2.2.3 (in .terraform/providers) does not match any of the checksums recorded in the dependency lock file

[2022-07-19T10:13:12.557Z] 

[2022-07-19T10:13:12.557Z] Terraform uses external plugins to integrate with a variety of different

[2022-07-19T10:13:12.557Z] infrastructure services. You must install the required plugins before running

[2022-07-19T10:13:12.558Z] Terraform operations.

[2022-07-19T10:13:12.558Z] -> Smoke tests FAILED!!
```

**Comment by marclop** [comment]
I think it happened because all three parallel Jenkins jobs are running in the same folder form what I see in the UI, and the terraform locks are preventing the job from running multiple terraform commands concurrently in the same folder (unintended behavior). I think the splitting of the lines isn't working correctly just yet.

In my machine I can run the command just fine and it returns the right output:

```
$ make smoketest/discover
/Users/marclop/repos/elastic/apm-server/testing/smoke/legacy-standalone-major-managed
/Users/marclop/repos/elastic/apm-server/testing/smoke/legacy-managed
/Users/marclop/repos/elastic/apm-server/testing/smoke/basic-upgrade
```

**Comment by simitt** [comment]
CI logic was adapted and test runs are parallelized now.

**Pull request merged**
