### PR TITLE
move trace.transaction_id to trace.transaction.id

### PR DESCRIPTION
**Pull request by jalvz**
implements #291 

note: this will break kibana UI badly

### CODE REVIEW

**Comment by roncohen** [comment]
@sqren @vanjacosic @makwarth cc

**Comment by roncohen** [comment]
Nice work!

**Comment by makwarth** [comment]
@jalvz @roncohen which version is this for?

**Comment by makwarth** [comment]
Leading up to GA in 6.2, I think we need to add breaking changes like this to a topic on APM weekly or something like that. It's too easy to miss mentions.

**Comment by makwarth** [comment]
Also, this includes a new task for the APM Server team to update the dashboards.

**Comment by roncohen** [comment]
Good point regarding dashboards. I've added an issue now: https://github.com/elastic/apm-server/issues/346. 

We can try to bring it up breaking changes in the weekly meeting. @jalvz will you put it on the agenda?

**Comment by makwarth** [comment]
There's also the [meta issue](https://github.com/elastic/apm-dev/issues/10). Add a Breaking changes checklist?

**Pull request merged**
