### PR TITLE
sampling: clarify storage limit reached error

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

When tail-based sampling fails due to the storage limit being reached, the error message looks something like this:

    flush pending writes: configured storage limit reached: no space left on device

This implies the disk is actually out of space, but the "no space left on device" is just an artefact of wrapping `syscall.ENOSPC` in `ErrLimitReached`. We remove the ENOSPC to avoid this confusion. Also, we now include the current badger DB size vs. stoarge limit in the error message, and add a unit test.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

1. Configure TBS, and a storage limit
2. Run some workload until the storage limit is reached
3. Check the logged error messages, ensure that they don't say "no space left on device"

## Related issues

None

### CODE REVIEW

**Review by lahsivjar — APPROVED** [review]
LGTM

**Review by marclop — APPROVED** [review]

**Comment by lahsivjar** [comment]
Tested this with `8.5.0-BC1` by setting storage limit to `2MB` with a sampling rate of `0.1`. Observed log message:

```
received error writing sampled trace: failed to flush pending writes: configured storage limit reached (current: 31170310, limit: 1800000)
```

**Pull request merged**
