### PR TITLE
Update backport files and changelog with 7.13 branch

### PR DESCRIPTION
**Pull request by jalvz**
## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

### CODE REVIEW

**Comment by jalvz** [comment]
jenkins retest this please

**Comment by jalvz** [comment]
@bmorelli25 any idea what i am doing wrong with docs?

**Comment by axw** [comment]
@jalvz there was a missing include in the top-level CHANGELOG.asciidoc -- I've just added it.

**Comment by jalvz** [comment]
ah thanks!

**Pull request merged**
