### PR TITLE
Set `<event>.duration.us` field in ingest pipeline

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Update package `model` to no longer set `transaction.duration.us` or `span.duration.us`, and instead set `event.duration`. Update our ingest pipelines to use `event.duration` to set the legacy fields, and then remove `event.duration`. This pipeline can be removed once when we are ready and able to update the APM UI to use `event.duration` directly.

I have listed this as a breaking change in the top-level changelog, as it will have visible effects for anyone not using the Elasticsearch output or the packaged ingest pipeline. I have not done this in the integration package changelog, as I assume the ingest pipeline is always in use there.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [x] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
~- [ ] Documentation has been updated~

## How to test these changes

Send transactions and spans with zero and non-zero durations, and ensure they each have `transaction.duration.us` or `span.duration.us` set, and do not have `event.duration` set.

## Related issues

Prerequisite of https://github.com/elastic/apm-server/issues/5999
Part of https://github.com/elastic/apm-server/issues/3565 and https://github.com/elastic/apm-server/issues/4120

### CODE REVIEW

**Comment by axw** [comment]
The integration tests are failing, so we'll need to update the package before merging this.

**Review by simitt — APPROVED** [review]
Change and handling of breaking change LGTM

**Comment by stuartnelson3** [comment]
confirmed with 772e8c1977e36f0c1d06c2af20f7cda893789365

1. start elasticsearch/kibana
2. start apm-server
3. ingest spans/transactions with the following program:
```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"go.elastic.co/apm"
)

func main() {
	version := "undefined"
	if len(os.Args) > 1 {
		version = os.Args[1]
	}
	name := fmt.Sprintf("apm-server-%s", version)

	tx := apm.DefaultTracer.StartTransaction(name, "type")
	ctx := apm.ContextWithTransaction(context.Background(), tx)
	span, ctx := apm.StartSpan(ctx, name, "type")
	span.Duration = 0
	span.End()
	tx.Duration = 0
	tx.End()
	<-time.After(time.Second)
	apm.DefaultTracer.Flush(nil)
	fmt.Printf("%s: %+v\n", name, apm.DefaultTracer.Stats())
}
```
4. check the transaction and span documents have `transaction.duration.us` and `span.duration.us` in the console
```
GET traces-apm-default/_search
{
  "sort" : [{ "@timestamp" : "desc" }]
}
```
5. repeat steps 3 and 4, modifying `span.Duration` and `tx.Duration` to be non-zero

**Pull request merged**
