### PR TITLE
beater/interceptors: add Timeout interceptor

### LINKED ISSUE #5049: Translate "context canceled" errors for gRPC requests
Like https://github.com/elastic/apm-server/issues/4484, but for gRPC (OTLP/Jaeger) requests. Example log message as things are currently:

> `{"log.level":"error","@timestamp":"2021-04-01T10:49:16.913+0800","log.logger":"beater.grpc","log.origin":{"file.name":"interceptors/logging.go","file.line":63},"message":"{error 26 0  context canceled}","source.address":"127.0.0.1","grpc.request.method":"/opentelemetry.proto.collector.trace.v1.TraceService/Export","event.duration":72260150,"grpc.response.status_code":"Unknown","error.message":"context canceled","ecs.version":"1.6.0"}`

We might also want to set the gRPC status code to `DEADLINE_EXCEEDED` if it's unknown/unset.

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Introduce an interceptor that intercepts `context.Canceled` and `context.DeadlineExceeded` errors, and sets the gRPC status code to DeadlineExceeded and message to "request timed out". Also, increment the request timeout counter.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

1. Using a gRPC-based client (OpenTelemetry or Jaeger), send some spans to the server with the timeout very low
2. Check server request logs: `grpc.response.status_code` should be "DeadlineExceeded", and `error.message` should be "request timed out".

I'm not sure what the best way to force a request timeout is. Using opentelemetry-go, I resorted to wrapping [`SpanExporter.ExportSpans`](https://github.com/open-telemetry/opentelemetry-go/blob/6db20e008dc272efaa29bb87d5d8341ad7c06da0/sdk/trace/span_exporter.go#L33), injecting a timeout there.

## Related issues

Closes #5049

### CODE REVIEW

**Review by jalvz — APPROVED** [review]

**Comment by stuartnelson3** [comment]
>I'm not sure what the best way to force a request timeout is. Using opentelemetry-go, I resorted to wrapping SpanExporter.ExportSpans, injecting a timeout there.

Doy ou still have the code you used available somewhere? I'm attempting to use [hotrod](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod) and lowering the apm-server read/write timeout to 1ns but still receiving "OK" messages

```
{"log.level":"info","@timestamp":"2021-05-03T14:07:35.149+0200","log.logger":"beater.jaeger","log.origin":{"file.name":"interceptors/logging.go","file.line":65},"message":"","grpc.request.method":"/jaeger.api_v2.CollectorService/PostSpans","event.duration":232662,"grpc.response.status_code":"OK","ecs.version":"1.6.0"}
```

**Comment by stuartnelson3** [comment]
My steps have been:

```
// start kibana + es
# ./scripts/compose.py start 7.13 --no-apm-server
// start jaeger agent
# docker run --rm -it --name jaeger-agent --network host -p6831:6831/udp -p5778:5778 -e REPORTER_GRPC_HOST_PORT=localhost:14250 jaegertracing/jaeger-agent:latest
// start hot rod jaeger example
# docker run --rm -it --network host -e JAEGER_AGENT_HOST=localhost -e JAEGER_AGENT_PORT=6831 -p8080-8083:8080-8083 jaegertracing/example-hotrod:latest all
```
And start the apm-server BC with the following config changes:

```diff
# diff ../apm-server.yml apm-server.yml
16c16
<   #read_timeout: 30s
---
>   read_timeout: 1us
19c19
<   #write_timeout: 30s
---
>   write_timeout: 1ns
430,437c430,437
<   #jaeger:
<     #grpc:
<       # Set to true to enable the Jaeger gRPC collector service.
<       #enabled: false
<
<       # Defines the gRPC host and port the server is listening on.
<       # Defaults to the standard Jaeger gRPC collector port 14250.
<       #host: "localhost:14250"
---
>   jaeger:
>     grpc:
>        # Set to true to enable the Jaeger gRPC collector service.
>       enabled: true
>
>        # Defines the gRPC host and port the server is listening on.
>        # Defaults to the standard Jaeger gRPC collector port 14250.
>       host: "localhost:14250"
647c647
<   #timeout: 90
---
>   timeout: 0
```
then I was hoping a span sent from the hotrod ui -> jaeger-agent -> apm-server would timeout because I set the read and write timeouts so low, but that hasn't happened so far.

**Comment by stuartnelson3** [comment]
Seems like those are only for HTTP and there doesn't appear to be a gRPC server "timeout" setting, which explains why that didn't do anything

**Comment by axw** [comment]
> Seems like those are only for HTTP and there doesn't appear to be a gRPC server "timeout" setting, which explains why that didn't do anything

Indeed, opened https://github.com/elastic/apm-server/issues/5222

**Comment by axw** [comment]
>> I'm not sure what the best way to force a request timeout is. Using opentelemetry-go, I resorted to wrapping SpanExporter.ExportSpans, injecting a timeout there.
>
> Doy ou still have the code you used available somewhere? I'm attempting to use hotrod and lowering the apm-server read/write timeout to 1ns but still receiving "OK" messages

I'm afraid not, sorry.

**Comment by simitt** [comment]
Is there more testing required on this?

**Comment by stuartnelson3** [comment]
there is! still to be confirmed

**Comment by stuartnelson3** [comment]
>I'm not sure what the best way to force a request timeout is. Using opentelemetry-go, I resorted to wrapping SpanExporter.ExportSpans, injecting a timeout there.

Followed the same route with 1ms and 1ns timeout

```go
func (e *timeoutExporter) ExportSpans(ctx context.Context, ss []*trace.SpanSnapshot) error {
	ctx, cancel := context.WithTimeout(ctx, time.Millisecond)
	defer cancel()
	return e.s.ExportSpans(ctx, ss)
}
```

tailed the docker logs and I wasn't able to see any, but client-side it was acknowledging timeoutes (`rpc error: code = DeadlineExceeded desc = context deadline exceeded`). This one is hard to catch.

**Comment by simitt** [comment]
@axw can you confirm that client side timeouts are what is expected here?

**Comment by axw** [comment]
Yes, if the client closes the connection due to the deadline being exceeded I would expect to see the error message.

@stuartnelson3 with the timeout set, did you see the server logging the requests at all? It may be that with the timeout set so low the context is being cancelled before a connection is even established.

**Comment by stuartnelson3** [comment]
bumped the timeout to 2ms and was able to see the timeouts successfully

**Comment by stuartnelson3** [comment]
```
{"log.level":"error","@timestamp":"2021-05-18T07:19:28.832Z","log.logger":"beater.grpc","log.origin":{"file.name":"interceptors/logging.go","file.line":63},"message":"{error 26 0  rpc error: code = DeadlineExceeded desc = request timed out}","source.address":"172.19.0.1","grpc.request.method":"/opentelemetry.proto.collector.trace.v1.TraceService/Export","event.duration":345768,"grpc.response.status_code":"DeadlineExceeded","error.message":"request timed out","ecs.version":"1.6.0"}
```

**Pull request merged**
