### PR TITLE
Only overwrite service.version if service.name is also set

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Motivation/summary

For metricsets the `service.version` is only overwritten if also `service.name` is given (see https://github.com/elastic/apm-server/pull/6407#issuecomment-950973237). It should be the same for transactions, errors, ...

## Checklist
- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

Ingest a transaction that only contains a `service.version`, but no `service.name`

### CODE REVIEW

**Review by axw — APPROVED** [review]
LGTM, thanks!

**Comment by tobiasstadler** [comment]
@axw I fixed the tests. `make test` and `make system-test` finished successfully on my machine.

**Comment by tobiasstadler** [comment]
Since this is some kind of bug fix, should it be back ported to 8.1?

**Comment by axw** [comment]
@tobiasstadler we have already frozen 8.1. Although it's arguable a bug fix, I'd prefer that it waits for 8.2. Is it causing any issues for you?

**Comment by tobiasstadler** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by stuartnelson3** [comment]
testing this was unsuccessful with 772e8c1977e36f0c1d06c2af20f7cda893789365

1. start elasticsearch/kibana
2. start apm-server
3. ingest span + transaction with the following program:
```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"go.elastic.co/apm/v2"
)

func main() {
	version := "undefined"
	if len(os.Args) > 1 {
		version = os.Args[1]
	}
	name := fmt.Sprintf("apm-server-%s", version)

	tracer, err := apm.NewTracer("", "1.0.0")
	if err != nil {
		panic(err)
	}
	tx := tracer.StartTransaction("name", "type")
	ctx := apm.ContextWithTransaction(context.Background(), tx)
	span, ctx := apm.StartSpan(ctx, "name", "type")
	span.End()
	tx.End()
	<-time.After(time.Second)
	tracer.Flush(nil)
	fmt.Printf("%s: %+v\n", name, tracer.Stats())
}
```
4. check the transaction document has no `service.version` set. In the console:
```
GET traces-apm-default/_search
{
  "sort" : [{ "@timestamp" : "desc" }]
}
```
`service.name` seems to have been set to the default value (the binary name) from the agent, and therefore `service.version` was also set.
I attempted to injest an ndjson document without a `service.name` set, but the apm server rejected it (`validation error: metadata: service: 'name': validation rule 'minLength(1)' violated`)

**Comment by axw** [comment]
@stuartnelson3 I'm not sure that your tests cover Tobias's changes.

The changes are related to overriding `service.name` and `service.version` at the event level, which the Go agent's API doesn't support. Your test above only affects the `service.name` and `service.version` set at the stream (metadata) level.

I've verified this with 8.2.0-BC1, using https://github.com/elastic/apm-server/blob/main/testdata/intake-v2/transactions_spans.ndjson#L2.

The first transaction overrides `service.name`, but does not specify `service.version`. I confirmed the `service.name` field is set to "serviceabc" but there is no `service.version` field set.

I then modified the document to override `service.version` but not `service.name`, and confirmed that neither are used and that `service.name` and `service.version` from metadata are both used.

Finally, I confirmed that if both `service.name` and `service.version` are specified in the overrides, both are used.

**Pull request merged**
