### PR TITLE
[6.x] Add backport config (#908)

### PR DESCRIPTION
**Pull request by sqren**
Backports the following commits to 6.x:
 - Add backport config  (#908)

### CODE REVIEW

**Comment by graphaelli** [comment]
why do we need this on the 6.x branch?

**Comment by sqren** [comment]
If you are on any other branch than master, backport currently won't work (since there is no backport config). This is the setup that works for Kibana. Thought it made sense here too but maybe people always work from master?

**Comment by graphaelli** [comment]
Makes sense, just checking if there was some other reason I was missing.  LGTM

**Comment by sqren** [comment]
@graphaelli can you merge?

**Pull request merged**
