### PR TITLE
Update beats framework to 990a5f7

### PR DESCRIPTION
**Pull request by graphaelli**
Mostly for #3277

### CODE REVIEW

**Comment by graphaelli** [comment]
@elastic/apm-server Anyone know what's going on with the vendored `github.com/gogo/protobuf/...` deps?  It seems we updated them but this beats update is trying to downgrade them?

**Comment by axw** [comment]
@graphaelli I think we need the newer version for Jaeger support. IIRC, nothing in libbeat depends on it, so it should be safe. @simitt does that sound right to you?

**Comment by simitt** [comment]
Agree with what @axw said, I needed to update the library when adding Jaeger support. 
I assume it tries to downgrade now after the vendoring file was fixed to include the `origin` in https://github.com/elastic/apm-server/pull/3272/files#diff-bd290170e2912d3e8694db1a151066e5R1947.

**Comment by graphaelli** [comment]
Good point @simitt, I wasn't thinking that origin was related.  github.com/gogo/protobuf has been updated in beats and reflect here now.  Sorry about the force push, was the most straightforward way to update this.

**Comment by graphaelli** [comment]
looking into this issue
```
 $ staticcheck github.com/elastic/apm-server/...
vendor/github.com/aws/aws-sdk-go-v2/service/ec2/customizations.go:36:20: NewDefaultRetryer not declared by package aws (compile)
vendor/github.com/aws/aws-sdk-go-v2/service/ec2/customizations.go:24:4: d.MinRetryDelay undefined (type *aws.DefaultRetryer has no field or method MinRetryDelay) (compile)
vendor/github.com/aws/aws-sdk-go-v2/service/ec2/customizations.go:25:4: d.MinThrottleDelay undefined (type *aws.DefaultRetryer has no field or method MinThrottleDelay) (compile)
vendor/github.com/aws/aws-sdk-go-v2/service/ec2/customizations.go:26:4: d.MaxRetryDelay undefined (type *aws.DefaultRetryer has no field or method MaxRetryDelay) (compile)
vendor/github.com/aws/aws-sdk-go-v2/service/ec2/customizations.go:27:4: d.MaxThrottleDelay undefined (type *aws.DefaultRetryer has no field or method MaxThrottleDelay) (compile)
```

**Comment by robgil** [comment]
# [Codecov](https://codecov.io/gh/elastic/apm-server/pull/3289?src=pr&el=h1) Report
> Merging [#3289](https://codecov.io/gh/elastic/apm-server/pull/3289?src=pr&el=desc) into [master](https://codecov.io/gh/elastic/apm-server/commit/291f11f24bedf35f3b0662f6da69dba6b96d0b38&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.



```diff
@@           Coverage Diff           @@
##           master    #3289   +/-   ##
=======================================
  Coverage   79.82%   79.82%           
=======================================
  Files         107      107           
  Lines        5625     5625           
=======================================
  Hits         4490     4490           
  Misses       1135     1135           
```

**Comment by graphaelli** [comment]
Two more origins were missing, added them manually and updated them with govendor.

**Pull request merged**
