### PR TITLE
correct typo for word can cited as 'an'

### PR DESCRIPTION
**Pull request by ElfBoyX**
Hi - I was reading docs on the web site and saw this, happy to start contributing.

From this public page: 
https://www.elastic.co/guide/en/apm/get-started/current/overview.html

Screen Shot 2019-06-06 at 4 28 42 PM

### CODE REVIEW

**Comment by madirey** [comment]
👍

**Comment by bmorelli25** [comment]
This was introduced in 7.0, I'll backport to the impacted branches. Thanks again @ElfBoyX, and welcome to the team :)

**Comment by ElfBoyX** [comment]
👍

**Comment by asantos3026** [comment]
👍

**Pull request merged**
