### PR TITLE
chore: use testcontainers to control compose's life cycle in system tests

### PR DESCRIPTION
**Pull request by mdelapenya**
## Motivation/summary
Let's use the library to start the compose file.

We are also adding support to destroy it if the `DESTROY_STACK` environment variable is set. Otherwise (default) will keep existing behaviour.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

I have considered changes for:
- [ ] documentation
- [ ] logging (add log lines, choose appropriate log selector, etc.)
- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))
- [x] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
- [ ] telemetry
- [ ] Elasticsearch Service (https://cloud.elastic.co)
- [ ] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)
- [ ] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)

## How to test these changes

```shell
$ cd systemtest
# will destroy the stack after tests run
$ DESTROY_STACK=true go test ./...
# won't destroy the stack after tests run
$ DESTROY_STACK= go test ./...
```

## Follow-ups
I'm not adding the new variable to Jenkins (maybe in at `script/common.bash`) because it will cause the containers to be destroyed before the `post` section in the Jenkins pipeline catures it to archive them in Jenkins UI.

### CODE REVIEW

**Review by v1v — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Review by axw — CHANGES_REQUESTED** [review]
Can you please add a motivation for these changes?

At the moment I don't see any benefit to using testcontainers for running docker-compose. There's more code to maintain which is a -1 for me; so what do we gain by adding it?

Also, what is the benefit of having `DESTROY_STACK` over directly running `docker-compose down` afterwards?

**Comment by mdelapenya** [comment]
> At the moment I don't see any benefit to using testcontainers for running docker-compose. There's more code to maintain which is a -1 for me; so what do we gain by adding it?
> 
> Also, what is the benefit of having `DESTROY_STACK` over directly running `docker-compose down` afterwards?

I added it with the initial intention of controlling the containers started in tests directly from the test runner (TestMain), but I did not wanted to change the current behaviour of keeping containers running, which is used by developers. I was tempted to add the variable only for Jenkins to keep it, but then I realised that if destroying the containers alongside the tests finish, would remove the ability to archive docker logs in the Jenkins UI, because it relies on running containers (we are brainstorming about this too).

I could simply and completely remove the shutdown method and its call, which would simplify the code (less code to maintain), still using testcontainers to spin up the compose file. I'd like to use the library instead of custom (but simple!) code because we are planning to add a WaitFor strategy for compose (see https://github.com/testcontainers/testcontainers-go/pull/261), which would help removing the waitForKibana method (again less code 😊). We can wait for that PR to be released preparing the code for it, or simply keeping it as is, what ever you see more convenient.

**Comment by axw** [comment]
> we are planning to add a WaitFor strategy for compose (see testcontainers/testcontainers-go#261), which would help removing the waitForKibana method (again less code blush).
> We can wait for that PR to be released preparing the code for it

Thanks for the additional context. Sounds like a good change, but let's wait for that feature before switching over please.

Re container destruction: even if we can automatically destroy containers at the end of the run, this can already be done by simply calling `docker-compose down` from the Jenkins script. What does this function+environment variable improve on?

**Comment by mdelapenya** [comment]
> > we are planning to add a WaitFor strategy for compose (see [testcontainers/testcontainers-go#261](https://github.com/testcontainers/testcontainers-go/pull/261)), which would help removing the waitForKibana method (again less code blush).
> > We can wait for that PR to be released preparing the code for it
> 
> Thanks for the additional context. Sounds like a good change, but let's wait for that feature before switching over please.

👍 

> Re container destruction: even if we can automatically destroy containers at the end of the run, this can already be done by simply calling `docker-compose down` from the Jenkins script. What does this function+environment variable improve on?

I added the variable as a way to keep the previous behavior. But I'm not married to this 😄, so I'm going to close it until we have the waitFor in the library side, and then we can discuss again about it.

Thank you @axw for your feedback!

**Pull request closed without merging**
