### PR TITLE
processor/otel: set default RepresentativeCount

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

When translating OpenTelemetry spans to transactions/spans,
set RepresentativeCount to 1. This is incorrect when sampling
is enabled, but it's better to have incorrectly scaled metrics
than none at all, which is what happens when RepresentativeCount
is zero.

Until/unless some tag along the lines of Jaeger's sampler.param
is added, users will have to mentally scale down the metrics
in proportion to the sampling rate, to find the actual event counts.

## Checklist

- [x] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

1. Run an OpenTelemetry-instrumented application which sends HTTP requests to another service
2. Configure to send data to APM Server, capture some requests and wait a minute or so (the aggregation interval).
3. Check the service map looks right
4. Check the service overview dependencies list has the expected entries

## Related issues

Closes https://github.com/elastic/apm-server/issues/4972

### CODE REVIEW

**Review by stuartnelson3 — APPROVED** [review]

**Comment by simitt** [comment]
Tested with BC4; with following setup:
*  `serviceB` : elastic-apm instrumented, calls `service-direct-otel`
* `service-direct-otel`: otel instrumented, calls `auth` service
* `auth` : elastic-apm instrumented, does not make external calls

Observed:
* the service map looks ok
Screenshot 2021-05-12 at 12 13 31

* the dependencies of `service-direct-otel` look ok
Screenshot 2021-05-12 at 12 13 02

* the service map for `service-direct-otel` shows `localhost:4001` instead of the service name `auth` - @axw is that expected?
Screenshot 2021-05-12 at 12 13 50

* `serviceB` shows no dependencies - I believe this is 
Screenshot 2021-05-12 at 12 12 52

**Comment by axw** [comment]
> the service map for service-direct-otel shows localhost:4001 instead of the service name auth - @axw is that expected?

Doesn't seem expected to me. I wouldn't expect the downstream to change based on the starting point for the service map. Maybe a UI bug? Can you share the docs, or code?

> serviceB shows no dependencies - I expected to see the service-direct-otel as dependency

Agreed... can you see any `metricset.name: service_destination` metrics for `service.name: serviceB`?

**Comment by simitt** [comment]
> Agreed... can you see any metricset.name: service_destination metrics for service.name: serviceB?

**Comment by simitt** [comment]
>  Can you share the docs, or code?

That is the relevant bit:
```
tracer := global.Tracer(tracerName)

	// send request to auth service
	if err := tracer.WithSpan(r.Context(), "Check Auth", func(ctx context.Context) error {
		// add some random wait time
		<-time.After(time.Duration((rand.Intn(5)+2)*100) * time.Millisecond)

		client := http.Client{Transport: othttp.NewTransport(http.DefaultTransport)}
		req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "http://localhost:4001/auth", nil)
		req.Header.Set("Authorization", r.Header.Get("Authorization"))
		resp, err := client.Do(req)
		if err != nil {
			return err
		}
		body, err := ioutil.ReadAll(resp.Body)
		if resp.StatusCode >= 400 {
			return errors.New(string(body))
		}
		return err
	}); err != nil {
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
```

**Comment by axw** [comment]
OK. So `destination.service.resource` will be `http://localhost:4001`, taken from the URL. I don't know why the service map would be different depending on the starting point. Seems likely to be a UI bug to me.

> No not for serviceB

Can you share the code for serviceB?

**Comment by simitt** [comment]
Relevant bits for serviceB:
```
var client = apmhttp.WrapClient(http.DefaultClient)

func handler(w http.ResponseWriter, r *http.Request) {
	req, _ := http.NewRequestWithContext(r.Context(), http.MethodGet, "http://localhost:4002/user", nil)
	req.Header.Set("Authorization", r.Header.Get("Authorization"))
	resp, err := client.Do(req)
	if err != nil {
		apm.CaptureError(r.Context(), err).Send()
		http.Error(w, err.Error(), 400)
		return
	}
	body, _ := ioutil.ReadAll(resp.Body)
	if resp.StatusCode >= 400 {
		err := errors.New(string(body))
		apm.CaptureError(r.Context(), err).Send()
		http.Error(w, err.Error(), resp.StatusCode)
		return
	}
	doSomething()
	w.Write(body)
}
```

**Comment by axw** [comment]
@simitt I can't see anything wrong with that. I just realised that having no service_destination metrics for serviceB can't have anything to do with OpenTelemetry, as you're using the Go Agent for serviceB. So I don't think it's relevant, but it would be good to get to the bottom of it. If you can share the full code I can try and investigate further.

**Comment by simitt** [comment]
Right, that should be unrelated, let's follow up on that offline. The opentelemetry related changes can be considered to be working as expected.

**Pull request merged**
