### PR TITLE
systemtest: add rate limiting test

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Add a system test which checks that rate limiting is wired up and effective. Remove existing (and [flaky](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-5426/2/tests)) Python-based rate limiting system tests, and rely on unit tests to cover more specific scenarios.

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
jenkins run the tests please

**Comment by simitt** [comment]
Did you mean to add rate limit specific unit tests that cover the removed test logic? If unit tests are already exhaustive enough, would you mind linking to them here so they can be compared on review?

**Comment by axw** [comment]
@simitt no, the new system test shows that rate limiting is wired up, including the use of X-Forwarded-For. The unit tests are at https://github.com/elastic/apm-server/blob/e18957ccee7ed8a81db2e1dc721a0e169e24850f/processor/stream/processor_test.go#L223

**Review by simitt — APPROVED** [review]

**Pull request merged**
