### PR TITLE
[test] custom elasticsearch config for sourcemaps

### LINKED ISSUE #3166: Add system test for sourcemapping with configured ES output
Add integration test for `apm-server.source_mapping.elasticsearch`, with `username+password` and with `api_key`.

### PR DESCRIPTION
**Pull request by simitt**
## Motivation/summary
Add system tests for `apm-server.rum.source_mapping.elasticsearch.*` configuration. So far only the configuration from the `output.elasticsearch` settings was tested. 
With this PR dedicated sourcemap elasticsearch configurations are tested, including tests for recently introduced `api_key` configuration and explicit username+password config.

The PR contains a bit of refactoring:
* Existing sourcemap tests are moved out of the large `test_integration.py` file to a dedicated `test_integration_sourcemap.py` file, following the structure for other tests. 
* Default values of shared functionality were changed to reflect the most common use case. 

## Checklist

~- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).~
- [x] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)
- [x] I have rebased my changes on top of the latest master branch

~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes~

~- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~

## How to test these changes
This PR is only touching system tests, so no need for any manual testing.

## Related issues
closes #3166

### CODE REVIEW

**Comment by simitt** [comment]
jenkins run the tests please

**Comment by axw** [comment]
It looks like this has caused a failure in another system test, because the API key that's being created isn't cleaned up.

**Comment by simitt** [comment]
Sure, I'll separate the commits next time. 

The test failures seem unrelated. 
* We already have an existing issue for the flaky test `test_invalidate_by_id` where no `invalidated_api_keys` are found https://github.com/elastic/apm-server/issues/3298.
* The `test_info_by_name` is new, but it fetches API Keys by _name_ `apm_integration_key`, wheres the newly introduced test creates a key named `test_sourcemap_apikey`.

**Comment by simitt** [comment]
@axw do you agree on the test failures being unrelated? If so I'd merge this in.

**Comment by axw** [comment]
@simitt that's fine by me. Looking at the by_name/by_id tests I can't see how they would be related.

**Pull request merged**
