### PR TITLE
add optional fields span.subtype and span.action

### PR DESCRIPTION
**Pull request by roncohen**
Implementing https://github.com/elastic/apm-server/issues/1617 (global issue: https://github.com/elastic/apm/issues/8) on the server

### CODE REVIEW

**Comment by jalvz** [comment]
agents sending subtype and action to a 6.4 install will see their requests rejected, right?

this could use a changelog entry, if it didn't get one

**Comment by simitt** [comment]
The Intake API allows additional fields, so `6.4` would simply ignore the additional fields but process the request. Otherwise we could never add fields, as every update on the agent side would be a breaking change

Good point regarding the changelog.

**Comment by roncohen** [comment]
thanks! will add change log entry

**Comment by roncohen** [comment]
https://github.com/elastic/apm-server/pull/1622

**Pull request merged**
