### PR TITLE
Do not strip leading 0s from traceIds and spanIds if the span source is jaeger

### LINKED ISSUE #4661: Jaeger does not strip 0 from trace/span IDs anlylonger
In elastic/apm-server#3849 I implemented support for stripping leading 0s from trace/span ids when they where created by Jaeger (Fixed #3837). Currently Jaeger is in the process of switching to full length ids (see jaegertracing/jaeger#1657).

Should the apm-server also switch to full length ids?

### PR DESCRIPTION
**Pull request by tobiasstadler**
Fixes #4661

### CODE REVIEW

**Review by axw — APPROVED** [review]
:heart: Thank you!

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
@tobiasstadler can you please add an entry to `changelogs/head.asciidoc`, under "Breaking changes"?

**Comment by tobiasstadler** [comment]
> @tobiasstadler can you please add an entry to `changelogs/head.asciidoc`, under "Breaking changes"?

done

**Pull request merged**
