### PR TITLE
add kubernetes and container fields

### PR DESCRIPTION
**Pull request by roncohen**
Fixes https://github.com/elastic/apm-server/issues/1621

### CODE REVIEW

**Comment by roncohen** [comment]
* will submit separate ECS alignment PR
* unrelated index pattern tests failing

**Comment by graphaelli** [comment]
What do you think about writing the `docker.container.*` fields directly to `container.*` instead?

**Comment by roncohen** [comment]
sure, seems like that would make it necessary to get https://github.com/elastic/apm-server/pull/1609. I've tried adding `container.id` by itself, but just adding it to common `_meta/fields.common.yml` will make the field conflict with the `container.id` from `_beats/libbeat/_meta/fields.ecs.yml`. Using "fields.ecs.yml" in the tests directly, requires us to add a bunch of exceptions in the tests for all the ECS fields that are not supported in this PR.

**Comment by graphaelli** [comment]
@roncohen What do you think of opening this directly against the 6.x branch, adding the `container.*` fields to our own schema there?  We can then deal with the testing challenges for this on master with less urgency.

**Comment by roncohen** [comment]
@graphaelli sounds good

**Comment by roncohen** [comment]
https://github.com/elastic/apm-server/pull/1644

**Comment by graphaelli** [comment]
I'm good with reopening this and merging.  We can tackle the ECS migration of these fields together with the other migrations.

**Comment by roncohen** [comment]
that didn't quite work. Will create a new PR against master instead.

**Comment by roncohen** [comment]
reopened here https://github.com/elastic/apm-server/pull/1651

**Pull request closed without merging**
