### PR TITLE
[ILM] Enable ILM by default when supported by configured ES output.

### PR DESCRIPTION
**Pull request by simitt**
This PR changes default value for `apm-server.ilm.enabled` from `false` to `auto`.

On startup or setup cmd the server determines if preconditions are fulfilled for enabling ILM.
ILM will be enabled when supported by configured ES, and no custom index and indices settings are configured for `output.elasticsearch`.

When `apm-server.ilm.enabled` is set to `false`, ILM is turned off. 

When `apm-server.ilm.enabled` is set to `true`, the server checks if custom `output.elasticsearch.index` or `output.elasticsearch.indices` configuration is set. If set, the server refuses to start up and fails with according error message. 
Otherwise the server also checks if ES supports ILM. Since the configured ES might not immediately be available (temporary connection loss, currently starting up, ..) the server cannot produce a hard failure. Once the server retrieves a connection to ES, it logs a warning and automatically falls back to ordinary index setup if ILM is not supported. 

* [x] changelog
* [x] notify cloud
* [ ] adapt docs (@bmorelli25 could you change the ILM docs to reflect these changes?)
* [ ] add testcases to testplan
* [x] adapt system tests to changed default

implements elastic/apm-server#2241 

====== 
Special testcases:
 * `./apm-server -e -E apm-server.ilm.enabled=true -E setup.template.name=custom -E setup.template.pattern=custom -E output.elasticsearch.index=custom` 
~refuses to startup with message 
```Exiting: `apm-server.ilm.enabled:true` is not allowed when custom `output.elasticsearch` index names are configured```~
Update: logs a message, enables ILM and ignores `index` configurtaion as otherwise it would be a breaking change to what users could have set up upgrading from `7.2`.
 * `./apm-server -e -E apm-server.ilm.enabled=true` with ES not supporting ILM: 
starts but falls back to ordinary index management and is logging: 
`ERROR	[index-management]	idxmgmt/manager.go:97	automatically disabled ILM as not supported by configured output`
 * `./apm-server -e  -E apm-server.ilm.enabled=auto -E setup.template.name=custom -E setup.template.pattern=custom -E output.elasticsearch.index=custom` 
falls back to ordinary index management and is logging: 
```WARN	[index-management]	idxmgmt/manager.go:97	Automatically disabled ILM as custom index settings configured.```
 * `./apm-server -e  -E apm-server.ilm.enabled=auto` with ES not supporting ILM 
falls back to ordinary index management and is logging: 
 `WARN	[index-management]	idxmgmt/manager.go:94	Automatically disabled ILM as not supported by configured output.`

Same behavior when testing with `setup` command.

### CODE REVIEW

**Comment by simitt** [comment]
Yes I can confirm it is behaving properly. You need to pass in `apm-server.ilm.enabled` instead of `ilm.enabled`.

**Comment by jalvz** [comment]
Great, thanks for confirming :man_facepalming: 

Some more observations, probably not very important:
- With ilm auto or true, _and_ no policies exist, logs say "Existing template will be overwritten, as overwrite is enabled" which might make someone believe _their_ template is overwritten

- With auto _and_ index or indices overwrite, there is a log line saying "Automatically disabled ILM", however with auto _and_ another output configured I couldn't find that line

- You said that `./apm-server -e -E apm-server.ilm.enabled=true -E setup.template.name=custom -E setup.template.pattern=custom -E output.elasticsearch.index=custom` should refuse to start, however that doesn't seem to be the case for me: it says "Custom index configuration ignored when ILM is enabled" and moves on

- `apm-server -e -E apm-server.ilm.enabled=true` with ES not supporting ILM does also fallback to ilm disabled (like auto)

**Comment by simitt** [comment]
@jalvz thanks for the feedback! Adressing your observations:

> With ilm auto or true, and no policies exist, logs say "Existing template will be overwritten, as overwrite is enabled" which might make someone believe their template is overwritten

There is dedicated log lines for `templates` and for `policies`. The line `Existing template will be overwritten, as overwrite is enabled.` is always printed when the template has `overwrite:true` set (which is the case when a new policy gets created), no matter if it exists or not. Right after this log line the next log line is more concrete about the template. I see how this can create confusion, changes in libbeat would be required for changing this though. I'll add it to my _improvement list_ for a follow up.

> With auto and index or indices overwrite, there is a log line saying "Automatically disabled ILM", however with auto and another output configured I couldn't find that line

Exactly, only when `output.elasticsearch.index` or `output.elasticsearch.indices` is customized in the config file, ILM will be disabled to respect those custom index settings. When ILM is set to `true` the index settings will be ignored. Would you expect different behavior?

> You said that ./apm-server -e -E apm-server.ilm.enabled=true -E setup.template.name=custom -E setup.template.pattern=custom -E output.elasticsearch.index=custom should refuse to start, however that doesn't seem to be the case for me: it says "Custom index configuration ignored when ILM is enabled" and moves on

Good catch, I updated the description. During implementation I realized this would be a breaking change and adapted handling to reflect `7.2` behavior: enable ILM and ignore index config.

> apm-server -e -E apm-server.ilm.enabled=true with ES not supporting ILM does also fallback to ilm disabled (like auto)

Yes. That is what we agreed on last week. It logs an error and continues with ILM disabled. Otherwise the server would be in a state where it is running but cannot connect to ES which would be a problematic scenario on cloud.

**Comment by jalvz** [comment]
Thanks for clarifications. Happy to see that overwriting template/index does not stop the server. Regarding second point:

> With auto and index or indices overwrite, there is a log line saying "Automatically disabled ILM", however with auto and another output configured I couldn't find that line

I meant that with `auto`, there is always a log line saying how `auto` is resolved; eg. if index is overwritten, log says "ILM disabled".
However when setting another output (eg logstash), I know that `auto` also resolves to false but I didn't find any "ILM disabled" in the logs (if i did it right).

**Comment by simitt** [comment]
> I meant that with auto, there is always a log line saying how auto is resolved; eg. if index is overwritten, log says "ILM disabled".
However when setting another output (eg logstash), I know that auto also resolves to false but I didn't find any "ILM disabled" in the logs (if i did it right).

Good point. The reason for that is though, that the whole `index-management` supporter and manager are not called by the framework in such cases.

**Comment by OrangeDog** [comment]
The documentation was not updated to mention the additional templates this now creates
https://www.elastic.co/guide/en/apm/server/7.3/configuration-template.html

As far as I can tell, it's no longer possible to control which ILM policy is used - there's no way to customise these additional templates?

It's very unfortunate that you added a whole extra system (`apm-server.ilm`) conflicting with the beats standard (`setup.ilm`). That was probably a bad idea.

**Comment by OrangeDog** [comment]
The documentation was not updated to mention the additional templates this now creates
https://www.elastic.co/guide/en/apm/server/7.3/configuration-template.html

As far as I can tell, it's no longer possible to control which ILM policy is used - there's no way to customise these additional templates?

It's unfortunate that you added a whole extra system (`apm-server.ilm`) conflicting with the beats standard (`setup.ilm`). That was probably a bad idea.

**Comment by simitt** [comment]
There is an [ILM specific documentation](https://www.elastic.co/guide/en/apm/server/7.3/manual-ilm-setup.html) showing how ILM can be manually set up, in case the default ILM policies are not suitable.

**Comment by OrangeDog** [comment]
> ILM can be manually set up

Indeed. But all other beats (and apm-server when `apm-server.ilm` is disabled) allow doing it via the `setup` config.

**Comment by simitt** [comment]
There's an open Issue for making policies configurable https://github.com/elastic/apm-server/issues/2240, which you are welcome to follow and participate in finding a solution.

APM Server certainly overlaps with other beats for many features. It does also have a lot of dedicated config options nested under `apm-server.*` though. One of the main reasons for using a dedicated ILM setting in APM Server is that the behavior is a bit different than in other beats, mainly because APM Server creates multiple different indices by default, with different needs for policies, whereas other beats don't. Therefore requirements for config options can easily drift apart and sharing the same config name for different options and behavior seems confusing.

**Comment by OrangeDog** [comment]
I would argue having apm-server suddenly start doing its own ILM, even though `setup.ilm.enabled: false` was equally (if not more) confusing.

**Comment by simitt** [comment]
I will look into how we can improve the documentation around the chosen ILM handling to avoid confusion around this in the future (cc @bmorelli25). 

APM Server did never actively support `setup.ilm.enabled` nor was this option documented. When ILM was introduced in APM Server it was introduced with the current config key `apm-server.ilm.*`

**Pull request merged**
