### PR TITLE
Change alpha to beta

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by watson** [comment]
jenkins, run tests please

**Comment by watson** [comment]
Not sure how to get tests running again, but I assume these failures are not related to this PR

**Comment by watson** [comment]
This needs to be backported to 6.1 btw. Not sure how to specify that as there's no 6.1 label?

**Comment by simitt** [comment]
jenkins, test this please.

**Comment by simitt** [comment]
@watson I added a backport label.

**Comment by watson** [comment]
@simitt how do we know which version to backport to?

**Comment by simitt** [comment]
We backport features only to the latest released minor afaik.

**Pull request merged**
