### PR TITLE
Add transaction.experience metrics

### LINKED ISSUE #3972: Add "experience" properties to RUM transaction schema
In the RUM agent we need to store structured metrics/metadata on transactions.

We have these requirements:
1. The data needs to be on the transaction (to avoid expensive queries)
2. The data needs to be indexed (filtering)
3. The structure needs to be defined in the intake schema (to use compression)

I propose to add the following structure to the transaction schema
```
{
    "experience": {
        "type": "object",
        "properties": {
            "cls": {
                "type": "number",
                "description": "The Cumulative Layout Shift metric",
                "minimum": 0
            },
            "tbt": {
                "type": "number",
                "description": "The Total Blocking Time metric",
                "minimum": 0
            },
            "fid": {
                "type": "number",
                "description": "The First Input Delay metric",
                "minimum": 0
            }
        }
    }
}
```

We should use the above structure for intake v2 and storage in ES. 

For intake v3 we only need to abbreviate `experience` to `exp`:

```
{
    "exp": {
        "type": "object",
        "properties": {
            "cls": {
                "type": "number",
                "description": "The Cumulative Layout Shift metric",
                "minimum": 0
            },
            "tbt": {
                "type": "number",
                "description": "The Total Blocking Time metric",
                "minimum": 0
            },
            "fid": {
                "type": "number",
                "description": "The First Input Delay metric",
                "minimum": 0
            }
        }
    }
}
```

We also [discussed defining metadata/metrics on transactions](https://github.com/elastic/apm/issues/293) for all agents but this doesn't seem to apply to backend agents.

### PR DESCRIPTION
**Pull request by axw**
## Motivation/summary

Add "experience" to the transaction schema, an
object which captures user/browser experience
metrics.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

I have considered changes for:
~- [ ] documentation~
~- [ ] logging (add log lines, choose appropriate log selector, etc.)~
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))~
- [x] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)
~- [ ] telemetry~
- [x] Elasticsearch Service (https://cloud.elastic.co)
- [x] Elastic Cloud Enterprise (https://www.elastic.co/products/ece)
- [x] Elastic Cloud on Kubernetes (https://www.elastic.co/elastic-cloud-kubernetes)

## How to test these changes

1. Start server
2. Send RUM transaction with experience metrics as described in #3972 (both v2 and v3)
3. Check the transaction docs for `transaction.experience` fields
4. Check that the fields are indexed

## Related issues

Closes #3972

### CODE REVIEW

**Comment by axw** [comment]
jenkins run the tests please

**Comment by axw** [comment]
@jahtalab can you please check that the elasticsearch fields are as you expect? I've got them stored as `transaction.experience.{cls,fid,tbt}`

**Comment by vigneshshanmugam** [comment]
@axw what do you think about storing them as full text field `totalBlockingTime`, `firstInputDelay` respectively to keep them in sync with other fields like `transasction.marks.agent.largesContentfulPaint`, `transasction.marks.agent.firstContentfulPaint`. 

Btw, I am not opposed to storing them as acronyms either as its easier for users to build UI on top of it.

**Comment by axw** [comment]
If we're comfortable using "cls" then I think it would make sense to also use "lcp" instead of largestContentfulPaint (or vice versa). I guess marks are a bit different though, as they end up exposed through the UI, whereas the experience metrics will presumably be used in aggregations only. I'll merge as is. Thanks!

**Pull request merged**
